### ISSUE TITLE
Memory Leak when downloading objects from google cloud bucket

### ISSUE THREAD

**Issue by georgianjalba** [GoogleCloudPlatform/google-cloud-dotnet#1604] opened 2017-11-01 13:45 UTC
Using Google.Cloud.Storage.V1 ( version 2.0.0.0 ) I have a memory leak when downloading images from a cloud bucket.

The code I used is the following:
[GCloud_MemoryLeak.txt](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/1434290/GCloud_MemoryLeak.txt)

If do the following operations I seem to get the memory back:
- dispose the StorageService inside of the StorageClient
- set the StorageClient variable to null
- force a GC.Collect()

Analyzing what occupies the memory it seems a lot of BufferyAsyncResult objects remain in memory.
Any ideas how I can clean the memory?

I tried using only one client to download all files and it seems to be a bit better but there is still a memory leak there. Anyway using one client is not a solution because I have multiple buckets with different access keys so I need to create clients for each.

**Comment by jskeet** [comment] 2017-11-01 13:49
Hmm. BufferAsyncResult isn't something we use explicitly ourselves as far as I'm aware. Are you sure these aren't just buffers that are allocated by .NET internally and reused? Does the memory actually grow without limit?

**Comment by georgianjalba** [comment] 2017-11-01 14:09
If I create a new client for each call to download an object the memory grows until my application crashes.
Here's a print screen I took right now using the memory profiler in Visual Studio. 
The difference between the first and the last snapshot I made was 1 GB.
![memoryprofilersnapshot](https://user-images.githubusercontent.com/854840/32278646-f5e79778-bf1e-11e7-81bb-52b768d2785c.png)

**Comment by jskeet** [comment] 2017-11-01 14:25
Hmm. That's surprising and worrying. I'm away this week so won't be able to look into it immediately, but when I'm back in the office I'll try to reproduce it. How large are the images? It looks like you're only downloading 50 files in total (10 files, 5 times each) unless I've mistaken something.

**Comment by georgianjalba** [comment] 2017-11-01 14:28
In the sample code I provided, yes it's 10 files 5 times each. When I did the memory profiling I increased the number of iterations so I could get the application to crash, which happened very quickly ( around 15 iterations ~ 150 files total  ). The files are not big the largest is 250 kb.

**Comment by jskeet** [comment] 2017-11-01 15:36
Thanks for all of the detail. One final question (hopefully) - what environment is this in? (Is it .NET desktop or .NET Core, and which version?)

**Comment by georgianjalba** [comment] 2017-11-01 18:41
The environment is .NET desktop (4.6.1)

**Comment by chrisdunelm** [comment] 2017-11-01 19:58
I can reproduce this problem; and it's almost certainly a recurrence of issue #409, which I've re-opened.  Each instance of `StorageClient` is creating an instance of `HttpClient`, which is known to not quickly release resources.

A workaround, as you discovered, is to dispose of the underlying `StorageService`. Nulling it out and forcing a GC is not required in the tests I've done.

We will consider how we can improve the case when multiple clients are required.

**Comment by jskeet** [comment] 2017-11-10 10:20
Now that StorageClient implements IDisposable, can we close this issue?

**Comment by jskeet** [comment] 2017-11-21 17:32
Closing - I still need to push the doc update though.

**Comment by georgianjalba** [comment] 2017-11-21 19:09
How long until the changes are pushed to the nuget package ?

**Comment by jskeet** [comment] 2017-11-21 21:53
I'm *hoping* to do a bit more work before releasing the next storage nuget package (which I'm hoping will be the 2.1.0 GA).

Workarounds for the moment:

- Use a single StorageClient, which would be a good idea if you can *anyway*
- Dispose of the StorageClient.Service explicitly

If you'd be willing to use a 2.1.0 beta, I could possibly release that sooner than the 2.1.0 GA.

**Comment by georgianjalba** [comment] 2017-11-22 08:16
Ok, thanks for the quick response. 
Since we are using this in a production environment I feel more comfortable waiting for the 2.1.0 GA release.

**Comment by jskeet** [comment] 2017-11-23 17:55
@georgianjalba: I've published 2.1.0-beta01. While it's not actually a GA release, I expect it to be fully stable. We're likely to do a GA release reasonably soon, when we've had some time for folks to try beta01.

**Comment by jskeet** [comment] 2017-11-24 16:52
Actually closing - I appear to have failed to do that before...

**Closed by jskeet** 2017-11-24 16:52 UTC
