### ISSUE TITLE
How to set fulfillmentMessages

### ISSUE THREAD

**Issue by JianikPatel** [GoogleCloudPlatform/google-cloud-dotnet#2134] opened 2018-05-09 14:52 UTC
How can i set this below with fulfillmentMessages[i].payload field in C#. I tryed it but not able to set because it's return type is Struct.
{
  "google": {
    "expectUserResponse": true,
    "richResponse": {
      "items": [
        {
          "simpleResponse": {
            "textToSpeech": "this is a simple response"
          }
        }
      ]
    }
  }
}

**Comment by jskeet** [comment] 2018-05-09 14:56
You need to create a Struct object, which can in turn have fields etc. I'm afraid we don't have a particularly good experience at the moment for creating a Struct, although one option is to create JSON yourself and parse that as a Struct with Struct.Parser.ParseJson.

**Comment by xjpatel** [comment] 2018-05-10 07:10
Thank you. But still my conversation is not left. I tryed below code : webhookResponse.Payload = Google.Protobuf.WellKnownTypes.Struct.Parser.ParseJson("{\"google\": { \"expectUserResponse\": false}} ");

**Comment by jskeet** [comment] 2018-05-10 07:27
I'm afraid I don't have any context for which API this is - is this Actions on Google? Please bear in mind that the maintainers of this repository aren't experts on the APIs themselves, only the client libraries. If you could specify which library you're using and ideally refer to the documentation you're using as well, that would really help. At the moment I don't have enough information to help you further.

**Comment by xjpatel** [comment] 2018-05-10 07:57
Yes i want to left my conversion. from the document i checked we have to set expectUserResponse field as  false. Please referred below document "https://dialogflow.com/docs/reference/api-v2/rest/Shared.Types/WebhookResponse" In this Payload field.

**Comment by jskeet** [comment] 2018-05-10 08:02
Okay, so it's the Dialogflow API. We didn't have that information before. Please could you show what code you're using? In particular, if you're implementing a web hook you mustn't use Json.NET to perform serialization or deserialization.

I would suggest that you log the response that you're sending, so you can check *exactly* what JSON it is being sent back.

**Comment by xjpatel** [comment] 2018-05-10 08:03
Please referred below json.
{
    "fulfillmentText": "We didn't find any order against your email please provide your registered phone number",
    "fulfillmentMessages": [],
    "source": "",
    "payload": {
        "fields": {
            "google": {
                "nullValue": 0,
                "numberValue": 0,
                "stringValue": "",
                "boolValue": false,
                "structValue": {
                    "fields": {
                        "expectUserResponse": {
                            "nullValue": 0,
                            "numberValue": 0,
                            "stringValue": "",
                            "boolValue": false,
                            "structValue": null,
                            "listValue": null,
                            "kindCase": 2
                        }
                    }
                },
                "listValue": null,
                "kindCase": 5
            }
        }
    },
    "outputContexts": [],
    "followupEventInput": null
}

**Comment by xjpatel** [comment] 2018-05-10 08:04
But still from google simulator my conversion is not left.

**Comment by xjpatel** [comment] 2018-05-10 08:06
I have set payload wia below line :  Payload = Google.Protobuf.WellKnownTypes.Struct.Parser.ParseJson("{\"google\": { \"expectUserResponse\": false}} ");

**Comment by jskeet** [comment] 2018-05-10 08:11
I'm afraid that's just a single line of code. I still don't know anything about how you're returning that JSON - or what from. Is this an ASP.NET Core app? An ASP.NET app? Something else?

It seems very likely to me that you just need to use the protobuf JSON serialization, but I can't help you do that while without more context - other than saying "call ToString() on your message and return that, it's already JSON".

**Comment by xjpatel** [comment] 2018-05-10 08:20
I am using ASP.Net WebAPI and below is the function which return httpresponse.   
 public HttpResponseMessage GoogleHome()
        {
            var speechprocessor = new GoogleVoice();
            NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();
            logger.Debug("\n----------------Request from Google Header------------------\n");
            logger.Debug(JsonConvert.SerializeObject(Request.Headers));
            logger.Debug("\n----------------------------------\n");
            var processedoutput = speechprocessor.jsonToWebHookModelTransform(HttpContext.Current.Request.InputStream);
            var response = Request.CreateResponse(HttpStatusCode.OK);
            var json = JsonConvert.SerializeObject(speechprocessor.ProcessIntent(processedoutput));

            var jsonSerializerSettings = new JsonSerializerSettings
            {
                ContractResolver = new Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver()
            };
            var interimObject = JsonConvert.DeserializeObject<WebhookResponse>(json);
            interimObject.Payload = Google.Protobuf.WellKnownTypes.Struct.Parser.ParseJson("{\"google\": { \"expectUserResponse\": false}} ");
            var myJsonOutput = JsonConvert.SerializeObject(interimObject, jsonSerializerSettings);

            logger.Debug("\n----------------Final Response------------------\n");
            logger.Debug(myJsonOutput);
            logger.Debug("\n----------------------------------\n");

            response.Content = new StringContent(myJsonOutput, Encoding.UTF8, "application/json");
            return response;
        }

**Comment by jskeet** [comment] 2018-05-10 08:30
Right - so as I said, the problem is that you're using Json.NET. Don't use that for *any* of the operations - it won't play well with protobuf JSON for various reasons.

- Use `MessageType.Parser.ParseJson` to parse any JSON you're receiving (where `MessageType` is whatever the message type of the request is)
- Call `ToString()` on the message to create JSON you can then return

(It's not clear to me what the `GoogleVoice` type is, or what `jsonToWebHookModelTransform` does, but hopefully this should help you.)

**Comment by jskeet** [comment] 2018-05-10 10:15
No, I don't have any examples - as I say, I have no experience with this API.

"MessageType" is just an example - whatever type you're trying to parse, e.g. `WebhookRequest.Parser.ParseJson(json)` will parse (and return) a `WebhookRequest`. Basically you should look at everywhere you're currently using `JsonConvert`, and use the protobuf parsing or formatting instead.

**Comment by xjpatel** [comment] 2018-05-10 10:28
I tryed but getting error like Google.Protobuf.InvalidProtocolBufferExcept.

**Comment by jskeet** [comment] 2018-05-10 10:30
Without knowing exactly what you're trying, or what the input is, I'm afraid it's very hard to help. If you could provide a small *complete* console app with hard-coded input (the input you need to parse), the output you're trying to provide and a detailed error message, I'd be able to help you much more easily. (The fewer times we need to go back and forth like this, the quicker you'll get to working code.)

**Comment by xjpatel** [comment] 2018-05-10 10:58
I have removed google package because of size issue. please add package and run that solution. you will get same error which i am getting right now.
[demo.zip](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/files/1991352/demo.zip)

**Comment by jskeet** [comment] 2018-05-10 11:26
I'm not quite sure why you've provided a large zip file here - the relevant code can be shown inline with no problems:

```csharp
using Google.Cloud.Dialogflow.V2;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo
{
    class Program
    {
        static void Main(string[] args)
        {
         
            var json = WebhookResponse.Parser.ParseJson("{\"google\": { \"expectUserResponse\": false}} ");

            Console.ReadLine();
        }
    }
}
```

Now you're trying to parse a response which should be a Struct - you've already got that code working:

```csharp
interimObject.Payload = Google.Protobuf.WellKnownTypes.Struct.Parser.ParseJson("{\"google\": { \"expectUserResponse\": false}} ");
```

Your code should:

- Fetch the request data
- Parse that using `var request = WebhookRequest.Parser.ParseJson(requestJson)`
- Create the `WebhookResponse` with whatever code you need
- Call `ToString()` on that response to provide the JSON for your web response

**Comment by xjpatel** [comment] 2018-05-10 11:31
Thank you but while parsing I ma getting error. Please refer attached screen shot
![image](https://user-images.githubusercontent.com/28751439/39867692-c6195924-5473-11e8-904c-ae5e4f1e444d.png)

**Comment by jskeet** [comment] 2018-05-10 11:36
Yes, because that's not valid data for the `WebhookResponse`. That's *just* the payload part, which as I say you've already handled elsewhere.  So you'd have *something* like:

```csharp
var payload = Struct.Parser.ParseJson("{\"google\": { \"expectUserResponse\": false}} ");
var response = new WebhookResponse
{
    FulfillmentMessages = { Message = new Message { Payload = payload } }
};
```

(Except with whatever else you need.)

**Comment by xjpatel** [comment] 2018-05-10 12:07
Now i am getting the response like {
    "FulfillmentText": "An invalid application ID was received from Google",
    "FulfillmentMessages": [],
    "Source": "",
    "Payload": {
        "Fields": {
            "google": {
                "NullValue": 0,
                "NumberValue": 0,
                "StringValue": "",
                "BoolValue": false,
                "StructValue": {
                    "Fields": {
                        "expectUserResponse": {
                            "NullValue": 0,
                            "NumberValue": 0,
                            "StringValue": "",
                            "BoolValue": false,
                            "StructValue": null,
                            "ListValue": null,
                            "KindCase": 4
                        }
                    }
                },
                "ListValue": null,
                "KindCase": 5
            }
        }
    },
    "OutputContexts": [],
    "FollowupEventInput": null
}

But GoogleWebhook expecting response in CamelCase so this will not work. Could you please suggest me how can i convert this response in CamelCase.

**Comment by jskeet** [comment] 2018-05-11 08:26
Closing this issue as I don't believe there's any actual bug in the library here - although I'm aware we definitely need samples for Dialogflow.

**Closed by jskeet** 2018-05-11 08:26 UTC
