### ISSUE TITLE
"Transport Closed" and "GOAWAY received" error on StreamAsync

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1891] opened 2018-02-06 08:27 UTC
For some days using firestore. Sometimes I got this error on using this library on aws dotnet lambda with this code

```C#
<PackageReference Include="Google.Cloud.Firestore" Version="1.0.0-beta02" />

////

var docID = await firestoreDB.Collection("users").Where(path,equal,id).StreamAsync().Where((resp) => resp.Exists).Select((resp) => resp.Id).FirstOrDefault()
```

The error is

```JSON
{
    "Grpc.Core.RpcException": [
        "Status(StatusCode=Unavailable, Detail=\"Transport closed\")"
    ]
}
```

and

```JSON
{
    "Grpc.Core.RpcException": [
        "Status(StatusCode=Internal, Detail=\"GOAWAY received\")"
    ]
}
```

Seem like it not really about `StreamAsync` api but it is the first API that would be get called on my server

**Comment by jskeet** [comment] 2018-02-06 08:32
Please give more details about how you've used the stream and anything else you've noticed:

- Do you consume the stream immediately, or do you create it and then only consume it much later?
- What's the timing in terms of when the channel is created (and last used) vs when you receive this error?
- Do you receive both kinds of error from the same code? Have you noticed any patterns as to which is produced when?

**Comment by jskeet** [comment] 2018-02-06 08:52
Thanks for the extra detail. The underlying Grpc code should refresh the channel these days, so I don't *think* it should be an idle channel issue. Have you noticed any patterns in terms of how often you're seeing it?

cc @schmidt-sebastian for anything Firestore-specific and @jtattermusch for any gRPC insight.

**Comment by Thaina** [comment] 2018-02-06 09:01
@jskeet It not very often just 5 times for since 2 days ago. But right now my server still in testing and I got this error after I run the client which connect to server which trigger many firestore API for some period of time. Then close the client to code some more and run it again, repeat this process eventually will got this error

Another possibility might be that. We have 2 programmer that could trigger server in the same time. Is it possible that firestore instance should not be call many api in the same time?

**Comment by jskeet** [comment] 2018-02-06 09:11
Concurrent requests should be absolutely fine, although I'm sure there are quota limits. (If you trigger a *deluge* of queries, that could explain the "go away" response, potentially?)

I'm not sure what you mean by "Then close the client to code some more" - what's the client here?

If you could keep an informal log of your activity and when you see the error, that could help to diagnose what's going on.

**Comment by Thaina** [comment] 2018-02-06 09:14
@jskeet The client is just unity program. But it not related, it just connect to server by HTTP response one at a time and only the server is responsible for connection to firestore

**Comment by Thaina** [comment] 2018-02-07 03:54
@jskeet Seem like GOAWAY might really came from quota limit. But howabout `Transport Closed` ?

**Comment by jskeet** [comment] 2018-02-07 06:06
I don't know at the moment I'm afraid, and I don't have time to look into it right now - I'm hoping @jtattermush or @schmidt-sebastian may have more suggestions.

**Comment by Thaina** [comment] 2018-02-07 06:28
Also have seen some mention about version of grpc https://github.com/grpc/grpc/issues/14088

They said they need to revert to 1.7.3

**Comment by jskeet** [comment] 2018-02-07 07:14
Interesting - I wasn't aware of that issue, and it could be related. Could you try upgrading to Grpc.Core 1.9.0?

**Comment by Thaina** [comment] 2018-02-07 07:15
Thanks for the suggestion. I will try

And so what Grpc version this repo normally used?

**Comment by Thaina** [comment] 2018-02-07 07:17
I use `<PackageReference Include="Google.Cloud.Firestore" Version="1.0.0-beta02" />` and so it was pull their own dependency, include all Grpc, from nuget by itself. If I specifically set Grpc version will it got overridden?

**Comment by jskeet** [comment] 2018-02-07 07:18
Different API client libraries are at different versions of gRPC, but normally when we do a minor version change, we'll go to the latest gRPC if we're confident in it. (We skipped the 1.8 series for other reasons.) We can't change dependency minor versions on only a patch version change, as that breaks semantic versioning - which is why there are different libraries with different dependencies.

I'm planning to do a significant update to all the dependencies to bring in the latest Protobuf *and* gRPC, but it takes a bit of work due to the dependency chain.

**Comment by jskeet** [comment] 2018-02-07 07:21
Yes, just add a dependency to Grpc.Core, version 1.9.0, and that's what will be used.

**Comment by jskeet** [comment] 2018-02-07 07:21
Yes, just add a dependency to Grpc.Core, version 1.9.0, and that's what will be used.

**Comment by Thaina** [comment] 2018-02-07 09:42
Using Grpc.Core version 1.9.0 and got the new error named `Socket Closed` and still got `Transport closed` but don't see goaway yet

also got the stack trace

```JSON
{"errorType":"RpcException","errorMessage":{"code":500,"message":"Status(StatusCode=Unavailable, Detail=\"Transport closed\")","stack":" at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.WhereSelectEnumerableAsyncIterator`2.<MoveNextCore>d__8.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.WhereSelectEnumerableAsyncIterator`2.<MoveNextCore>d__8.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n at LambdaHandler.<myHandler>d__262.MoveNext() in /opt/atlassian/pipelines/agent/build/Program.cs:line 157","extra":"Status(StatusCode=Unavailable, Detail=\"Transport closed\")"}}
```


```JSON
{"errorType":"RpcException","errorMessage":{"code":500,"message":"Status(StatusCode=Unavailable, Detail=\"Socket closed\")","stack":" at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.WhereSelectEnumerableAsyncIterator`2.<MoveNextCore>d__8.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.WhereSelectEnumerableAsyncIterator`2.<MoveNextCore>d__8.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Linq.AsyncEnumerable.<FirstOrDefault_>d__165`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n at LambdaHandler.<myHandler>d__262.MoveNext() in /opt/atlassian/pipelines/agent/build/Program.cs:line 157","extra":"Status(StatusCode=Unavailable, Detail=\"Socket closed\")"}}
```

**Comment by jtattermusch** [comment] 2018-02-07 10:43
These seems to be the places where the messages are coming from:
https://github.com/grpc/grpc/blob/f4a94b61266dc468af2de213ea50b997a39b7508/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L2445
https://github.com/grpc/grpc/blob/f4a94b61266dc468af2de213ea50b997a39b7508/src/core/lib/iomgr/tcp_posix.cc#L420

It looks like that the remote endpoint might just be closing the TCP connection on you (are sure that you're not hitting the quota limit?).

What might help is adding additional tracing, e.g.
GRPC_VERBOSITY=debug GRPC_TRACE=tcp,connectivity_state,http,http2_stream_state   
https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

**Comment by Thaina** [comment] 2018-02-07 10:47
@jtattermusch I will add that env and wait for the next encounter

**Comment by jtattermusch** [comment] 2018-02-07 10:51
Sg, feel tree to experiment with what tracers give you the best insight into what's going on.

**Comment by Thaina** [comment] 2018-02-08 06:29
Use that env variable and got this chunk

```
D0208 06:11:25.640375 140480629462784 src/core/lib/iomgr/tcp_posix.cc:354: read: error={"created":"@1518070285.640353739","description":"Socket closed","fd":114,"file":"src/core/lib/iomgr/tcp_posix.cc","file_line":421,"grpc_status":14,"target_address":"ipv4:216.58.197.234:443"}
D0208 06:11:25.640446 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1350: perform_stream_op_locked: SEND_INITIAL_METADATA{key=3a 73 63 68 65 6d 65 ':scheme' value=68 74 74 70 73 'https', key=3a 6d 65 74 68 6f 64 ':method' value=50 4f 53 54 'POST', key=3a 70 61 74 68 ':path' value=2f 67 6f 6f 67 6c 65 2e 66 69 72 65 73 74 6f 72 65 2e 76 31 62 65 74 61 31 2e 46 69 72 6
I0208 06:11:25.640478 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: :scheme: https
I0208 06:11:25.640486 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: :method: POST
I0208 06:11:25.640494 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: :path: /google.firestore.v1beta1.Firestore/RunQuery
I0208 06:11:25.640502 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: :authority: firestore.googleapis.com:443
I0208 06:11:25.640513 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: x-goog-api-client: gl-dotnet/2.0.0 gccl/1.0.0-beta02 gapic/1.0.0-beta02 gax/2.2.1 grpc/1.9.0
I0208 06:11:25.640521 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: google-cloud-resource-prefix: projects/komodevth/databases/(default)
I0208 06:11:25.640531 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: authorization: Bearer ya29.c.ElpcBRyk45fsIMIsQ_ad7eVdCtYid8cOnRpt7_oLlvq3i6ykx9rWarU4u7NTd-daK2QLgUJfyWthNsJslR9BlGjZzjxsDVu0e6NvE2nuczcD4ecjdgK3yznVWtQ
I0208 06:11:25.640541 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: te: trailers
I0208 06:11:25.640549 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: content-type: application/grpc
I0208 06:11:25.640556 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: user-agent: grpc-csharp/1.9.0 grpc-c/5.0.0 (linux; chttp2; glossy)
I0208 06:11:25.640564 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: grpc-accept-encoding: identity,deflate,gzip
I0208 06:11:25.640571 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1329: HTTP:0:HDR:CLI: accept-encoding: identity,gzip
D0208 06:11:25.640580 140480629462784 src/core/ext/transport/chttp2/transport/stream_lists.cc:123: 0x7fc40800e950[0][cli]: add to waiting_for_concurrency
D0208 06:11:25.640590 140480629462784 src/core/ext/transport/chttp2/transport/stream_lists.cc:69: 0x7fc40800e950[0][cli]: pop from waiting_for_concurrency
D0208 06:11:25.640598 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1134: HTTP:CLI: Allocating new grpc_chttp2_stream 0x14112b8 to id 31
D0208 06:11:25.640606 140480629462784 src/core/ext/transport/chttp2/transport/stream_lists.cc:123: 0x7fc40800e950[31][cli]: add to writable
D0208 06:11:25.640614 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:821: W:0x7fc40800e950 CLIENT state WRITING -> WRITING+MORE [START_NEW_STREAM]
D0208 06:11:25.640628 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1198: complete_closure_step: t=0x7fc40800e950 0x14110b8 refs=4 flags=0x0003 desc=op->on_complete err="No Error" write_state=WRITING+MORE
D0208 06:11:25.640639 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1350: perform_stream_op_locked: RECV_INITIAL_METADATA; on_complete = 0x1411178
D0208 06:11:25.640649 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1198: complete_closure_step: t=0x7fc40800e950 0x1411178 refs=0 flags=0x0000 desc=op->on_complete err="No Error" write_state=WRITING+MORE
D0208 06:11:25.640668 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1350: perform_stream_op_locked: RECV_MESSAGE; on_complete = 0x14111b8
D0208 06:11:25.640678 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1198: complete_closure_step: t=0x7fc40800e950 0x14111b8 refs=0 flags=0x0000 desc=op->on_complete err="No Error" write_state=WRITING+MORE
D0208 06:11:25.640738 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1198: complete_closure_step: t=0x7fc40800e950 0x14110b8 refs=3 flags=0x0003 desc=send_initial_metadata_finished err={"created":"@1518070285.640690255","description":"Pending writes failed due to stream closure","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2063,"refe
D0208 06:11:25.640767 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1198: complete_closure_step: t=0x7fc40800e950 0x14110b8 refs=2 flags=0x0003 desc=send_trailing_metadata_finished err={"created":"@1518070285.640690255","description":"Pending writes failed due to stream closure","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2063,"ref
D0208 06:11:25.640792 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1198: complete_closure_step: t=0x7fc40800e950 0x14110b8 refs=1 flags=0x0003 desc=on_write_finished_cb err={"created":"@1518070285.640690255","description":"Pending writes failed due to stream closure","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2063,"referenced_err
D0208 06:11:25.640813 140480629462784 src/core/ext/transport/chttp2/transport/stream_lists.cc:91: 0x7fc40800e950[31][cli]: remove from writable
D0208 06:11:25.640828 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1198: complete_closure_step: t=0x7fc40800e950 0x14110b8 refs=0 flags=0x0003 desc=recv_trailing_metadata_finished err="No Error" write_state=WRITING+MORE
D0208 06:11:25.640856 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2502: ipv4:216.58.197.234:443: Start BDP ping err={"created":"@1518070285.640684351","description":"Endpoint read failed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2410,"occurred_during_write":2,"referenced_errors":[{"created":"@1518070285.640381824","description
D0208 06:11:25.640878 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2515: ipv4:216.58.197.234:443: Complete BDP ping err={"created":"@1518070285.640684351","description":"Endpoint read failed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2410,"occurred_during_write":2,"referenced_errors":[{"created":"@1518070285.640381824","descript
D0208 06:11:25.640896 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:821: W:0x7fc40800e950 CLIENT state WRITING+MORE -> WRITING [begin write in current thread]
D0208 06:11:25.640921 140480629462784 src/core/lib/iomgr/tcp_posix.cc:649: WRITE 0x7fc410004e70 (peer=ipv4:216.58.197.234:443): 17 03 03 00 25 00 00 00 00 00 00 00 20 13 ce 9f a9 be 36 aa 09 80 cb da dc 79 2e 79 a7 8d 21 b2 84 02 f0 16 ba 81 e6 27 27 3e '....%....... .....6......y.y..!........''>'
D0208 06:11:25.640976 140480629462784 src/core/lib/iomgr/tcp_posix.cc:679: write: "No Error"
D0208 06:11:25.640990 140480629462784 src/core/lib/transport/connectivity_state.cc:114: CONWATCH: 0x13fed30 client_channel: unsubscribe notify=0x7fc4240254e0
D0208 06:11:25.641000 140480629462784 src/core/lib/transport/connectivity_state.cc:166: SET: 0x7fc42c077250 (null): READY --> IDLE [selected_changed+reresolve] error=(nil) "No Error"
D0208 06:11:25.641008 140480629462784 src/core/lib/transport/connectivity_state.cc:192: NOTIFY: 0x7fc42c077250 (null): 0x7fc408012be8
D0208 06:11:25.641037 140480629462784 src/core/lib/transport/connectivity_state.cc:166: SET: 0x13fed30 client_channel: READY --> IDLE [lb_changed] error=(nil) "No Error"
D0208 06:11:25.641048 140480629462784 src/core/lib/transport/connectivity_state.cc:117: CONWATCH: 0x7fc42c077250 (null): from IDLE [cur=IDLE] notify=0x7fc418007a98
D0208 06:11:25.641067 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:821: W:0x7fc40800e950 CLIENT state WRITING -> IDLE [finish writing]
D0208 06:11:25.641076 140480629462784 src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2691: set connectivity_state=4
D0208 06:11:25.641111 140480629462784 src/core/lib/transport/connectivity_state.cc:166: SET: 0x7fc40800ebf0 client_transport: TRANSIENT_FAILURE --> SHUTDOWN [close_transport] error=0x7fc418000d20 {"created":"@1518070285.640836005","description":"Delayed close due to in-progress write","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":595,"referenced_errors":[{"create
```

By the logger I have it would be too hard to export the full log but the bottom chunk json is like this

```JSON
{
    "created": "@1518070285.640753063",
    "description": "Error in HTTP transport completing operation",
    "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
    "file_line": 1209,
    "referenced_errors": [
        {
            "created": "@1518070285.640690255",
            "description": "Pending writes failed due to stream closure",
            "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
            "file_line": 2063,
            "referenced_errors": [
                {
                    "created": "@1518070285.640684351",
                    "description": "Endpoint read failed",
                    "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
                    "file_line": 2410,
                    "occurred_during_write": 2,
                    "referenced_errors": [
                        {
                            "created": "@1518070285.640381824",
                            "description": "Secure read failed",
                            "file": "src/core/lib/security/transport/secure_endpoint.cc",
                            "file_line": 154,
                            "referenced_errors": [
                                {
                                    "created": "@1518070285.640353739",
                                    "description": "Socket closed",
                                    "fd": 114,
                                    "file": "src/core/lib/iomgr/tcp_posix.cc",
                                    "file_line": 421,
                                    "grpc_status": 14,
                                    "target_address": "ipv4:216.58.197.234:443"
                                }
                            ]
                        },
                        {
                            "created": "@1518070285.640257675",
                            "description": "GOAWAY received",
                            "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
                            "file_line": 1095,
                            "http2_error": 0,
                            "raw_bytes": "session_timed_out"
                        }
                    ]
                }
            ]
        },
        {
            "created": "@1518070285.640690255",
            "description": "Pending writes failed due to stream closure",
            "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
            "file_line": 2063,
            "referenced_errors": [
                {
                    "created": "@1518070285.640684351",
                    "description": "Endpoint read failed",
                    "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
                    "file_line": 2410,
                    "occurred_during_write": 2,
                    "referenced_errors": [
                        {
                            "created": "@1518070285.640381824",
                            "description": "Secure read failed",
                            "file": "src/core/lib/security/transport/secure_endpoint.cc",
                            "file_line": 154,
                            "referenced_errors": [
                                {
                                    "created": "@1518070285.640353739",
                                    "description": "Socket closed",
                                    "fd": 114,
                                    "file": "src/core/lib/iomgr/tcp_posix.cc",
                                    "file_line": 421,
                                    "grpc_status": 14,
                                    "target_address": "ipv4:216.58.197.234:443"
                                }
                            ]
                        },
                        {
                            "created": "@1518070285.640257675",
                            "description": "GOAWAY received",
                            "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
                            "file_line": 1095,
                            "http2_error": 0,
                            "raw_bytes": "session_timed_out"
                        }
                    ]
                }
            ]
        },
        {
            "created": "@1518070285.640690255",
            "description": "Pending writes failed due to stream closure",
            "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
            "file_line": 2063,
            "referenced_errors": [
                {
                    "created": "@1518070285.640684351",
                    "description": "Endpoint read failed",
                    "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
                    "file_line": 2410,
                    "occurred_during_write": 2,
                    "referenced_errors": [
                        {
                            "created": "@1518070285.640381824",
                            "description": "Secure read failed",
                            "file": "src/core/lib/security/transport/secure_endpoint.cc",
                            "file_line": 154,
                            "referenced_errors": [
                                {
                                    "created": "@1518070285.640353739",
                                    "description": "Socket closed",
                                    "fd": 114,
                                    "file": "src/core/lib/iomgr/tcp_posix.cc",
                                    "file_line": 421,
                                    "grpc_status": 14,
                                    "target_address": "ipv4:216.58.197.234:443"
                                }
                            ]
                        },
                        {
                            "created": "@1518070285.640257675",
                            "description": "GOAWAY received",
                            "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
                            "file_line": 1095,
                            "http2_error": 0,
                            "raw_bytes": "session_timed_out"
                        }
                    ]
                }
            ]
        }
    ],
    "target_address": "ipv4:216.58.197.234:443"
}
```

**Comment by apolcyn** [comment] 2018-02-09 08:03
@Thaina in the original post you seem to have received an `Internal` status code, and you mentioned that starting with the 1.9.0 release you have not seen it, but you are still seeing the `Unavailable` status codes. And for the `unavailable` status codes - at what frequency are you seeing these? 

I'm not actually certain what error code is sent for going above usage quota (as mentioned above as a possible cause) but I wouldn't be surprised if these errors are a result of that; there is not anything immediately obvious from that log.

Also, are you able to see any pattern to when/how the errors occur? E.g., do the errors occur only after using a connection for some certain time period?

**Comment by Thaina** [comment] 2018-02-09 08:35
@apolcyn I'm not sure too but I actually use blaze plan so is it really be related to quota?

There is no pattern actually and my coworker said it somehow frequent. Every 2-3 launching the app will got this error once

**Comment by apolcyn** [comment] 2018-02-09 18:00
do we have a rough guess of the number of RPC's that occurred in this time though?

that is, do you have a rough order of magnitude estimate of the number of `failed/successful` calls you are seeing to `firestoreDB` ?

**Comment by Thaina** [comment] 2018-02-10 04:16
@apolcyn If rough estimation of firestore API call I think it would be around 20 times for this happen once

But I don't know about internal rpc call

**Comment by jskeet** [comment] 2018-02-20 16:53
Just received this myself loading data into Datastore - the process had been running for approximately two hours.

> Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="GOAWAY received")

**Comment by jskeet** [comment] 2018-02-28 09:31
@jtattermusch @apolcyn Ping for any more thoughts on this?

**Comment by jtattermusch** [comment] 2018-03-02 11:20
Looking at the detailed log above,   the root cause of the problem seem to be this:
```
{
                            "created": "@1518070285.640257675",
                            "description": "GOAWAY received",
                            "file": "src/core/ext/transport/chttp2/transport/chttp2_transport.cc",
                            "file_line": 1095,
                            "http2_error": 0,
                            "raw_bytes": "session_timed_out"
                        }
```

which IMHO translates to: the remote side has hung up on us (by sending GOAWAY) with explanation "session_timed_out" (In HTTP2 the GOAWAY frame has a payload containing debug info).  How long was the connection (channel) active before this error happened. I don't know details about the Firestore API, but perhaps the sessions are time-limited and you need to reconnect from time to time (that would make sense, as it's hard to make sure the same TCP/IP connection stay alive for hours without breaking).

**Comment by jskeet** [comment] 2018-03-02 11:23
> that would make sense, as it's hard to make sure the same TCP/IP connection stay alive for hours without breaking

That feels like something that gRPC should be taking care of though, shouldn't it? I'd expect this to be part of the general channel management side of things. (Note that it's not just Firestore - I saw this with Datastore too.) I'd really rather this wasn't pushed up to applications to manage.

**Comment by jskeet** [comment] 2018-04-20 08:09
@Thaina: Are you still seeing this? If so, have you tried updating to gRPC 1.11.0?

**Comment by Thaina** [comment] 2018-04-20 11:12
@jskeet Fortunately I have not found these error anymore since march

**Comment by jskeet** [comment] 2018-04-20 11:26
Great! Will close this issue then.

**Closed by jskeet** 2018-04-20 11:26 UTC
Labels: priority: p2, status: investigating, type: bug
