### ISSUE TITLE
Consider giving a story for F#

### ISSUE THREAD

**Issue by haf** [GoogleCloudPlatform/google-cloud-dotnet#682] opened 2017-01-04 12:32 UTC
Google Cloud platform may be in a good position to get a lot of uptake from the vibrant F# community. With Suave, Logary, expecto, VSCode and an alternative OS – Linux or OS X, it follows easily to try an alternative cloud, like Google Cloud.

I've started on a tutorial series/book about how to get started with Kubernetes, F# and Suave that may be of interest https://github.com/haf/linux-intro-course/tree/master/chapter-04 (also see the previous chapters).

GCloud has the opportunity to be the more open-source based cloud and while doing so mention F# alongside C#.

**Comment by jskeet** [comment] 2017-01-04 13:19
Well *any* .NET language should work - C#, F#, VB etc. But we would certainly expect most of our users to be using C#, simply because of numbers of developers. If anything we're doing is particularly difficult to work with in F# and can be simplified without making it worse for C# developers, I'd definitely be interested - but I doubt that we'll start providing all our samples in F# as well as C#, for example.

**Comment by haf** [comment] 2017-01-04 13:29
My point here is "the story". I don't doubt all examples could be easily presented in F# or even F# treated as its own eco-system, actually. For great benefit for your platform, too.

**Comment by jskeet** [comment] 2017-01-04 13:40
> I don't doubt all examples could be easily presented in F# or even F# treated as its own eco-system, actually.

I suspect you're vastly underestimating the cost of creating and maintaining well-written, idiomatic, fully explained examples, I'm afraid. Obviously we're happy if the community wants to provide such things, but I doubt that we'll be treating it as a peer to C# any time soon. Aside from anything else, I'd expect any F# developer to be sufficiently aware of C# to allow them to easily understand any C# samples anyway, so the actual benefit of providing F# samples is significantly reduced.

**Comment by haf** [comment] 2017-01-04 13:46
I don't agree that I don't know the cost: have a look at the docs [I maintain for Logary](https://github.com/logary/logary#logary-v4), [Suave](https://suave.io/), [Expecto](https://github.com/haf/expecto#expecto) or the [Linux tutorial](https://github.com/haf/linux-intro-course).

I'd be happy with having a space for community to maintain such docs.

Many F# devs aren't previous .Net developers. Many are brand new programmers. Some are just hobbyists. F# idiomatic examples are different from C# examples, too. So newbies become rather confused if they are mixed. Especially now, with .Net Core, F# is shaping up have a *very* compelling story as a functional-first programming language on the linux platform. Looking at it from this perspective shows that F#-specific docs could be greatly beneficial.

**Comment by jskeet** [comment] 2017-01-04 14:02
You could take the same approach another community member does for the REST APIs: she has her own [github repo with samples](https://github.com/LindaLawton/Google-Dotnet-Samples). We could certainly then link to that in the documentation.

We could *potentially* add F# snippets in the same way that we have C# ones in the API top-level docs, but I wouldn't want to start presenting both F# and C# examples in the reference documentation without thinking really carefully about how we'd make it work.

Please bear in mind that the APIs we have right now are only the tip of the iceberg - and coordinating between multiple product teams across multiple languages really does have a cost. It's much simpler to maintain examples for a library you own end-to-end, and where you can set your own deadlines. Again, I'll raise this internally, but given how much work we already have to do, I don't think adding F# samples for everything - or even working out the infrastructure to integrate community-written ones alongside the  others - is the most valuable use of our time.

**Comment by realvictorprm** [comment] 2017-08-31 09:33
I'm willing to help here to. You can ask the F# Software Foundation for colabortation @jskeet, e.g. I can serve here as listener. 

Most important is however, to give us a chance to help you.

**Comment by jskeet** [comment] 2017-08-31 10:56
The problem is still one of time at the moment. Even if other people are providing a lot of the examples, collaboration is expensive. Yes, we would like to make the libraries ideal for every .NET language - but we've got to focus on where the opportunity is greatest, which for the moment is C#.

I'm not saying that this won't or shouldn't happen - but we don't have time to work on it right now.

**Comment by jskeet** [comment] 2017-12-06 15:04
Closing for now having added this to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/BACKLOG.md)

**Closed by jskeet** 2017-12-06 15:04 UTC
Labels: documentation, priority: p2

**Comment by realvictorprm** [comment] 2017-12-06 19:22
Thank you!


Official member of the F# Board of Trustee's. F# for fun and profit!

Am 06.12.2017 16:04 schrieb "Jon Skeet" <notifications@github.com>:
