### ISSUE TITLE
[error] An empty string was provided, but is not valid

### ISSUE THREAD

**Issue by Thaina** [GoogleCloudPlatform/google-cloud-dotnet#1925] opened 2018-02-26 03:56 UTC
```C#
var d	= await firestoreDB.Value.Collection("players").OrderBy("SomeField").StartAfter("").Limit(1).StreamAsync().FirstOrDefault();
```

Throw this error

```
   at Google.Api.Gax.GaxPreconditions.CheckNotNullOrEmpty(String argument, String paramName)
   at Google.Cloud.Firestore.PathUtilities.ValidateId(String id, String paramName)
   at Google.Cloud.Firestore.Query.CreateCursor(Object[] fieldValues, Boolean before)
   at Google.Cloud.Firestore.Query.StartAfter(Object[] fieldValues)
   at LambdaHandler.<>c.<<Main>b__269_0>d.MoveNext() in D:\Users\Admin\Documents\komodo\testdotnet\Program.cs:line 293
```

I think this might be intentional but is it really not valid? I just wan to query every document that has that field be any string. Empty string is also valid value

**Comment by jskeet** [comment] 2018-02-26 09:33
This is not an issue in the .NET Client. I'd suggest asking on the [Google Group](https://groups.google.com/forum/#!forum/firebase-talk) for Firebase discussions - this isn't language-specific.

The simple fix is just to not call `StartAfter` though.

**Comment by Thaina** [comment] 2018-02-26 09:47
@jskeet I see. I think it is only cause in this sdk. Thanks

**Comment by jskeet** [comment] 2018-02-26 09:52
Oh, hang on - sorry, I'd thought this was a server-side validation. Will reopen and check more carefully later. I'd have to check why we're calling ValidateId.

**Comment by Thaina** [comment] 2018-02-26 09:59
@jskeet before I reply to you I already check with jssdk and it seem it also cause (somehow difference) error in jssdk too. It look like startAt would not handle empty string in any sdk because it will construct a path  `/path/{key}/` which would become `/path//`

I don't know it was intentional or not

**Comment by jskeet** [comment] 2018-02-26 12:16
I wouldn't expect to see this problem unless your ordering was actually `OrderBy(FieldPath.DocumentId)`, not `OrderBy("SomeField")`. If you're just ordering by a string field, it should just be converting the string into a value.

If you *are* ordering by document ID, this is behaving as I'd expect it to - you have to provide a valid reference path to start at.

**Comment by Thaina** [comment] 2018-02-26 12:52
I see. Does it means only orderby docid was difference from other field?

By somefield I put there it actually is a variable and I test it with docid first. I would try to test with other field tomorrow. Might be my fault here

**Comment by jskeet** [comment] 2018-02-26 13:35
I don't understand the question in your first paragraph, I'm afraid. Could you restate it? If you're asking whether docid fields are handled differently to other field names, the answer is yes - the cursor value for a docid field must be either a DocumentReference or a string that's a valid path within the collection.

**Comment by Thaina** [comment] 2018-02-26 13:41
You understand it correctly. Thanks

**Comment by jskeet** [comment] 2018-02-27 06:45
Closing as this is working as intended.

**Closed by jskeet** 2018-02-27 06:45 UTC
Labels: status: investigating, type: bug
