### ISSUE TITLE
Google.Cloud.BigQuery.V2 only show 5 errors

### ISSUE THREAD

**Issue by AlexandreOuellet** [GoogleCloudPlatform/google-cloud-dotnet#2154] opened 2018-05-17 19:48 UTC
I have a CreateLoadJobOptions that has MaxBadRecords set to a high number.  As long as I don't hit this number, the job complete, but I only see a maximum of 5 errors.  Since, I'm trying to have BigQuery load ~18k CSV files (DeltaDNA dump into an S3 bucket, which was then transfered and extracted into a directory), I would like to instead have a way to ask BigQuery to transfer everything it can, and nothing from files that have errors, and report which files have failed instead.

**Comment by AlexandreOuellet** [comment] 2018-05-18 15:27
Yeah, for the 3rd point, I am already starting to work in batches (but the main issue that I face is most files contains at least 1 of those errors.  DeltaDNA seems to output stuff in a non-standard way for some specific metrics, I might need to think of another strategy).

The 2nd point is exactly as you stated : MaxBadRecords is set to say 10.  Once it detects 10 errors, the whole job fails, but I still only get 5 errors.  If it detects 9 errors, the whole job is completed, but I'm still only shown 5 errors within the job's result.

**Comment by jskeet** [comment] 2018-05-18 15:35
I'll ask about the 5 errors part - that may well just be a limitation of BigQuery's error reporting (e.g. to avoid job resources becoming huge).

If most of your files have at least one error, that suggests that even if you *could* say "0 errors per file, but try each file separately" then you'd still lose most of the data.

Will leave this open until I've resolved the "only 5 errors" part, but I doubt that there's any change to make for the rest.

**Comment by AlexandreOuellet** [comment] 2018-05-18 15:43
For the lost data/errors in files : Yes.  I'm still trying to figure out a way to quickly parse those, but that's still an issue for me.  It seems that DeltaDNA can't output JSon strings in a parse-able format.

**Comment by jskeet** [comment] 2018-05-21 15:06
@AlexandreOuellet: Right, I've a) reproduced the problem and b) been in touch with the BigQuery folks. It looks like that "only reporting 5 errors" is by design and currently not configurable. Is this something you'd like me to pursue further, or have your own investigations into the causes of breakage meant that it's not a problem for you anyway?

**Comment by AlexandreOuellet** [comment] 2018-05-22 14:03
Lots of stuff going on on my end, so it was put on hold for the moment.

If possible, I would like to have a way to identify which files have failed during a transfer from GCS to BigQuery.  Since I have ~18k files, it would take a long time to essentially ask BQ to transfer each single file, 1 by 1, then identifying which one fails (Essentially 18k).  If there is a way to do it with all of the 18k, then get a list of files that fails, that would be great.  I could then keep a list of which files have failed, still continue with the rest of the transfer for the files that did not fail, and then work my way through those that did fail.

**Comment by jskeet** [comment] 2018-05-22 14:13
Thanks for the extra information.

I've found there's already an internal feature request for more information - both in terms of showing more errors, and giving more detail about all of them. I'll add a link to this issue there, so the team knows about more customer demand.

For the moment I'll close this issue if that's okay, as I don't believe there's anything more that can be done in *this* repo.

**Closed** 2018-05-22 14:22 UTC
