### ISSUE TITLE
Could not load type 'Google.Api.Gax.ScopedCredentialProvider'

### ISSUE THREAD

**Issue by smadigan-dexcom** [GoogleCloudPlatform/google-cloud-dotnet#1097] opened 2017-06-06 21:31 UTC
`Could not load type 'Google.Api.Gax.ScopedCredentialProvider' from assembly 'Google.Api.Gax, Version=2.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47'.
   at Google.Cloud.BigQuery.V2.BigQueryClient.Create(String projectId, GoogleCredential credential)`

It appears that the type may actually be Google.Api.Gax.Rest.ScopedCredentialProvider?

nuget config for the project:
  `<package id="Google.Api.CommonProtos" version="1.1.0" targetFramework="net451" />
  <package id="Google.Api.Gax" version="2.0.0-beta01" targetFramework="net451" />
  <package id="Google.Api.Gax.Grpc" version="2.0.0-beta01" targetFramework="net451" />
  <package id="Google.Api.Gax.Rest" version="2.0.0-beta01" targetFramework="net451" />
  <package id="Google.Apis" version="1.27.1" targetFramework="net451" />
  <package id="Google.Apis.Auth" version="1.27.1" targetFramework="net451" />
  <package id="Google.Apis.Bigquery.v2" version="1.27.1.877" targetFramework="net451" />
  <package id="Google.Apis.Core" version="1.27.1" targetFramework="net451" />
  <package id="Google.Apis.Storage.v1" version="1.27.1.860" targetFramework="net451" />
  <package id="Google.Cloud.BigQuery.V2" version="1.0.0-beta10" targetFramework="net451" />
  <package id="Google.Cloud.Iam.V1" version="1.0.0-beta09" targetFramework="net451" />
  <package id="Google.Cloud.Logging.Log4Net" version="1.0.0-beta10" targetFramework="net451" />
  <package id="Google.Cloud.Logging.Type" version="1.0.0" targetFramework="net451" />
  <package id="Google.Cloud.Logging.V2" version="1.0.0" targetFramework="net451" />
  <package id="Google.Cloud.Monitoring.V3" version="1.0.0-beta06" targetFramework="net451" />
  <package id="Google.Cloud.PubSub.V1" version="1.0.0-beta09" targetFramework="net451" />
  <package id="Google.Cloud.Storage.V1" version="2.0.0-beta01" targetFramework="net451" />
  <package id="Google.Protobuf" version="3.3.0" targetFramework="net451" />
  <package id="Grpc.Auth" version="1.3.0" targetFramework="net451" />
  <package id="Grpc.Core" version="1.3.0" targetFramework="net451" />`

**Comment by jskeet** [comment] 2017-06-06 21:50
You've updated the version of most APIs, but you haven't updated `Google.Cloud.BigQuery.V2` to 1.0.0-beta11 - that was expecting to use Google.Api.Gax v1.0, whereas the new version will expect Google.Api.Gax v2.0-beta01. If you update to the latest version of Google.Cloud.BigQuery.V2, all should be well.

I'm hoping to release Google.Api.Gax v2.0 GA this week, so there'll be another set of updates to *all* libraries at the same time.

I'm closing this issue as the cause and solution are known, and I don't believe there's any more work to do here - do reopen it if this doesn't fix the problem, of course.

**Closed by jskeet** 2017-06-06 21:50 UTC

**Comment by smadigan-dexcom** [comment] 2017-06-06 22:21
ugh.  forgot to check the "include prerelease" box in nuget package manager when checking for updates....
thanks!
