### ISSUE TITLE
Creating a new table on CSV upload doesnt work

### ISSUE THREAD

**Issue by ssgtcookie** [GoogleCloudPlatform/google-cloud-dotnet#1164] opened 2017-07-04 08:27 UTC
```
// This example uploads data to an existing table. If the upload will create a new table
// or if the schema in the CSV isn't identical to the schema in the table (for example if the
// columns are in a different order), create a schema to pass into the call.
TableSchema schema = null;
```

This does not work as expected. The API throws an error instead of creating a new table in visual studio. The snippet does not demonstrate the auto-schema functionality that is needed to create a new table. The error:

**_Message[Not found: Table project-id-here:dataset-id-here.table-id-here] Location[ - ] Reason[notFound] Domain[global]_**

**Comment by jskeet** [comment] 2017-07-04 08:31
Could you post the call you're using, just for clarity? (I'm assuming this is BigQuery, based on the error etc. It's always worth saying as this repo deals with lots of different APIs.)

**Comment by ssgtcookie** [comment] 2017-07-04 08:42
BigQuery indeed in [this file](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Snippets/BigQueryClientSnippets.cs) on lines 334 till 337. The upload CSV snippet will fail already on line [318](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.Snippets/BigQueryClientSnippets.cs#L318) where you select a table that does not exist.

**Comment by jskeet** [comment] 2017-07-04 08:48
You mean the snippet fails if you change it to use a different table ID? (The fixture ensures that the table already exists.) Sorry, I'm finding it hard to tell what you're actually running at this point.

The comment says that if you're trying to create a new table, you should specify a schema. It doesn't look like it's *trying* to demonstrate any auto-schema functionality, so it's not clear what you expected or why. Could you clarify please?

**Comment by ssgtcookie** [comment] 2017-07-04 09:15
I was running a code snippet to upload some CSV file from my PC _without_ using the fixtures. The project-ID and dataset-ID were existing but the table-ID was not. My goal is to create a new table based on the CSV file if it isnt there yet by using auto-schema. The uploadCsv function does not supply an auto-schema function or the option to add the flag which is possible when using the CLI.

But I think last part is true indeed, the snippet is not _trying_ to demonstrate that sadly. In that light I think it's best to close this issue and mark this issue more as an suggestion to add the auto-schema functionality to the uploadCsv function. There are quite some scenario's in which you don't want to insert the table-schema by hand and use the auto-detect option.

**Comment by jskeet** [comment] 2017-07-04 09:28
Yes, I'll close this as everything appears to be working as intended. (For future issues, it would be really helpful if you could show a minimal example of exactly what you're running from the start. A short but complete console app is ideal.)

A feature request for auto-schema detection is entirely reasonable - and I'd assume it would apply to other upload types as well as CSV. I'll have to investigate what the API provides.

**Closed by jskeet** 2017-07-04 09:28 UTC
Labels: API: bigquery
