### ISSUE TITLE
Methods in TextToSpeech library throw Unimplemented Exceptions

### ISSUE THREAD

**Issue by telpirion** [GoogleCloudPlatform/google-cloud-dotnet#2280] opened 2018-06-22 22:05 UTC
Using the TextToSpeech.V1 library, calls to TextToSpeechClient.ListVoices() and TextToSpeechClient.SynthesizeSpeech() raise "Unimplemented Exceptions."

Library:
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/apis/Google.Cloud.TextToSpeech.V1

Code I'm using:

```
using System;
using Google.Cloud.TextToSpeech.V1;

namespace TextToSpeech
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            try
            {
                System.Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS",
                    "/path/to/credentials/file");
                ListVoices();
                CreateAudio("Hello, this is synthetic speech!");

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        public static void ListVoices()
        {
            TextToSpeechClient client = TextToSpeechClient.Create();
            var response = client.ListVoices(new ListVoicesRequest
            {
                LanguageCode = "en"
            });

            foreach (Voice voice in response.Voices) // Exception
            {
                Console.WriteLine(voice.Name);
            }
        }

        public static void CreateAudio(string text)
        {

            TextToSpeechClient client = TextToSpeechClient.Create();
            var response = client.SynthesizeSpeech(new SynthesizeSpeechRequest
            {
                Input = new SynthesisInput
                {
                    Text = text
                },
                Voice = new VoiceSelectionParams
                {
                    LanguageCode = "en-US",
                    SsmlGender = SsmlVoiceGender.Female
                },
                AudioConfig = new AudioConfig
                {
                    AudioEncoding = AudioEncoding.Mp3
                }
            });

            Console.WriteLine(response.AudioContent); // Exception
            // TODO Write the content to file.
        }
    }
}
```

**Comment by jskeet** [comment] 2018-06-23 06:54
I apologise - I know what's going on here. The API is present and the code itself is fine, but the API only works for whitelisted projects at the moment. I shouldn't have released the NuGet package yet... unfortunately I got caught up in conferences and forgot the reason I was holding off!

I'll unlist the package for the moment to avoid other users having the issue.

Thanks very much for reporting this, and for doing so with a complete example that made it so easy for me to reproduce.

**Comment by jskeet** [comment] 2018-06-23 07:48
I've unlisted the package. Closing this bug for now as there's no more work to do here until the API becomes more widely available.

**Closed by jskeet** 2018-06-23 07:48 UTC
Labels: priority: p1, status: investigating, type: bug
