### ISSUE TITLE
Constantly growing memory use when using Google.Cloud.Logging.V2 

### ISSUE THREAD

**Issue by andreasp79** [GoogleCloudPlatform/google-cloud-dotnet#1060] opened 2017-05-19 21:12 UTC
Starting from empty project, improrting the Google.Cloud.Logging.V2 package, and using the following stress test results in an application that constantly grows memory use:

using System;
using System.Collections.Generic;
using System.Threading;
using Google.Cloud.Logging.V2;

class CloudLogStressTest
{
    static void Main(string[] args)
    {
        StartTest();

        Console.ReadLine();
    }

    private static void WriteLogEntry(string message, Google.Cloud.Logging.Type.LogSeverity severity)
    {
        LoggingServiceV2Client CloudLogClient = LoggingServiceV2Client.Create();
        LogName logName = new LogName("hades-star-21480733", "cloud-log-stress");

        LogNameOneof LogResource = LogNameOneof.From(logName);

        Google.Api.MonitoredResource Monitor = new Google.Api.MonitoredResource { Type = "global" };

        var client = LoggingServiceV2Client.Create();

        string threadName = System.Threading.Thread.CurrentThread.Name;
        if (string.IsNullOrEmpty(threadName))
        {
            threadName = System.Threading.Thread.CurrentThread.ManagedThreadId.ToString();
        }

        LogEntry logEntry = new LogEntry
        {
            LogName = logName.ToString(),
            Severity = severity,
            TextPayload = string.Format("[{0}]: {1}", threadName, message)
        };

        IDictionary<string, string> entryLabels = new Dictionary<string, string>
            {
                { "size", "large" },
                { "color", "red" }
            };

        client.WriteLogEntriesAsync(LogResource, Monitor, entryLabels, new[] { logEntry });
    }

    public static void StartTest()
    {
        for (int i = 0; i < 40; ++i)
        {
            ThreadStart ts = new ThreadStart(threadEntry);
            Thread t = new Thread(ts);
            t.Start();
        }
    }

    static void threadEntry()
    {
        Random rng = new Random();

        int num = 0;

        while (true)
        {
            int type = rng.Next(4);

            string msg = string.Format("This is an excellent message {0} from thread {1} at time {2}",
                num++, Thread.CurrentThread.ManagedThreadId, Environment.TickCount);

            WriteLogEntry(msg, Google.Cloud.Logging.Type.LogSeverity.Info);

            Thread.Sleep(rng.Next(50));
        }
    }
}

This is not specific to the stress test function, a production server using similar logging functionality keeps growing memory use over time in a rate dependent on the number of logs sent.

This also seems to happen in log4net when using the Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender.

A memory snapshot indicating the growing use can be found here: 
http://stackoverflow.com/questions/44053347/memory-leak-using-google-cloud-logging-v2-package-in-c-sharp

**Comment by chrisdunelm** [comment] 2017-06-06 14:39
@andreasp79 I'm unable to reproduce this, but I suspect it may be due to calling `WriteLogEntriesAsync` faster than the log entries can be sent off your machine.
Because the code calls `WriteLogEntriesAsync` but does not await the returned `Task`, the code will continue to queue log entries for sending, whatever the underlying rate at which the created `Task`s are being completed; leading to an every-increasing number of `Task`s in memory.

`GoogleStackdriverAppender` will also buffer log-entries in memory, but will bound the memory-use to 1,000 log-entries by default; discarding old log-entries if more than 1,000 are locally queued for sending.

If you have more data that suggests this isn't the case, please let us know.

**Comment by andreasp79** [comment] 2017-06-06 17:31
Perhaps the sample isn't good for reproducing the actual problem then, but there is definitely a leak happening over time when logging from multiple threads, regardless if using sync/async methods, or whether going through log4net. 

We have tried a lot of configurations (sync/async methods on either Google.Cloud.Logging.V2/GoogleStackdriverAppender or Google.Apis.Logging.v2) and the only thing that fixed it was having a separate thread that collects all log texts from other threads and sends them periodically in a synchronous manner.

Here is our memory usage on our production server over the past week (10GB of RAM). The server is supposed to be using less than 1GB for all other tasks. The drop is when we deployed the fix described above. That machine certainly has no issue sending logs fast enough. Before the drop the server was using the GoogleStackdriverAppender. The patterns of logging are identical before and after the drop.

![capture](https://user-images.githubusercontent.com/2314654/26842850-6f0a93dc-4aab-11e7-8454-b443cfb20a3f.PNG)

We also have an open case with google cloud support on this.

**Comment by chrisdunelm** [comment] 2017-06-06 20:15
@andreasp79 Do you mean that you now have only one thread calling `WriteLogEntries`?
Roughly what timescale is that memory use graph over?
Which runtime and version is this using? (i.e is it full .NET runtime; or .NET Core; and which version at you targeting?)

Please can you confirm if my understanding is correct with the following:
* When you had multiple threads all directly calling `WriteLogEntries` (or `WriteLogEntriesAsync`) you saw the memory use increase?
* When you had multiple threads using log4net, configured with the `GoogleStackdriverAppender` you saw the memory use increase? How did you configure log4net? Using an xml config file? Programmatically? If possible, please can you post the configuration?

Thanks.

**Comment by andreasp79** [comment] 2017-06-06 21:08
Yes, our fix was to only have a single thread call the Entries.write API (we are now using Google.Apis.Logging.v2 directly, haven't verified behavior with the Google.Logging.V2 library).

The time period for the graph is 7 days. We have written about 700MB of logs during that time. We have confirmed from our staging server that memory growth never stop, the server eventually crashes regardless of total RAM.

We are targeting full .NET Framework 4.5.2.

Your understanding is correct, when we had multiple threads sending logs directly we had memory leaking over time, both with the API and log4net. Our log4net config is very simple based on the samples:

<log4net>
    <appender name="StackDriverAppender" type="Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender,Google.Cloud.Logging.Log4Net">
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%property{log4net:HostName} [%thread]: %message" />
      </layout>
      <projectId value="..." />
      <logId value="vm-gameserver" />
    </appender>

    <root>
      <level value="ALL" />
         <appender-ref ref="StackDriverAppender"/>
    </root>
  </log4net>

**Comment by jskeet** [comment] 2017-06-08 07:13
We think we've pinned this down to a gRPC bug: https://github.com/grpc/grpc/issues/11434

**Comment by jskeet** [comment] 2017-06-21 08:52
This is a P0 bug, but there's little more work for *us* to do here - we're just waiting on the gRPC 1.4 release, which I'm hoping will be soon. That will trigger a raft of releases for us, at which point I can close this issue.

**Comment by jskeet** [comment] 2017-06-22 11:48
Fixed - the Google.Cloud.Logging.V2 package v2.0.0 shouldn't exhibit this (as it depends on Grpc.Core 1.4.0)

**Closed** 2017-06-22 11:51 UTC
Labels: Priority: P0, Status: Release Blocking, Type: Bug
