### ISSUE TITLE
memory leak in dotnet speech client

### ISSUE THREAD

**Issue by sg-blake** [GoogleCloudPlatform/google-cloud-dotnet#1824] opened 2018-01-11 06:31 UTC
In the attached sample code, I’m experiencing a memory leak using function Call2(), while function Call1() works normally.
Could you check my problem please?

Call1() uses Recognize, and Call2() uses StreamingRecognize.
Creating a Channel instance only once and reusing it would control the memory increase,
but I need to handle a situation where a single client makes multiple speech recognition requests simultaneously,
so sharing one channel is an unavailable option.

NuGet Package Version Info
Google.Cloud.Speech.V1 : v1.0.0
Grpc.Core : v1.8.0

```
// [START speech_quickstart]

using Google.Cloud.Speech.V1;
using System;
using Google.Apis.Auth.OAuth2;
using Grpc.Auth;
using System.IO;
using System.Threading;

namespace GoogleCloudSamples
{
    public class QuickStart
    {
        public static void Main(string[] args)
        {
            try
            {
                for (int i = 0; i < 100; ++i)
                {
                    //Call1();
                    Call2();
                    Console.WriteLine($"Next: {i}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }

        static public void Call2()
        {
            String credentialsFilePath = "./my_credentials.json";
            GoogleCredential googleCredential;
            using (Stream m = new FileStream(credentialsFilePath, FileMode.Open))
            {
                googleCredential = GoogleCredential.FromStream(m);
            }

            var channel = new Grpc.Core.Channel(SpeechClient.DefaultEndpoint.Host, googleCredential.ToChannelCredentials());
            
            var speech = SpeechClient.Create(channel);
            var stream = speech.StreamingRecognize();

            #region _WriteStream
            /*
            var task = speech.StreamingRecognize().WriteAsync(
                new StreamingRecognizeRequest()
                {
                    StreamingConfig = new StreamingRecognitionConfig()
                    {
                        Config = new RecognitionConfig()
                        {
                            Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                            SampleRateHertz = 16000,
                            LanguageCode = "en",
                        },
                        InterimResults = true,
                    }
                });
            
            Task printResponses = Task.Run(async () =>
            {
                while (await speech.StreamingRecognize().ResponseStream.MoveNext(default(CancellationToken)))
                {
                    String transcript = "";

                    foreach (var result in speech.StreamingRecognize().ResponseStream.Current.Results)
                    {
                        foreach (var alternative in result.Alternatives)
                        {
                            transcript += alternative.Transcript;
                            Console.Write(alternative.Transcript);
                        }
                        if (result.IsFinal)
                        {
                        }
                    }
                }
            });*/
            #endregion

            stream.WriteCompleteAsync().Wait();
            channel.ShutdownAsync().Wait();
        }

        static public void Call1()
        {
            String credentialsFilePath = "./my_credentials.json";
            GoogleCredential googleCredential;
            using (Stream m = new FileStream(credentialsFilePath, FileMode.Open))
            {
                googleCredential = GoogleCredential.FromStream(m);
            }

            var channel = new Grpc.Core.Channel(SpeechClient.DefaultEndpoint.Host, googleCredential.ToChannelCredentials());

            var speech = SpeechClient.Create(channel);
            var response = speech.Recognize(new RecognitionConfig()
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = 16000,
                LanguageCode = "en",
            }, RecognitionAudio.FromFile("audio.raw"));
            
            foreach (var result in response.Results)
            {
                foreach (var alternative in result.Alternatives)
                {
                    Console.WriteLine(alternative.Transcript);
                }
            }

            channel.ShutdownAsync().Wait();
        }
    }
}
// [END speech_quickstart]

```

**Comment by jskeet** [comment] 2018-01-11 12:47
Thanks for reporting this. I'm at a conference this week, but I'll try to reproduce it next week. (I'm also at a different conference for a lot of next week, but I've got a couple of days to try to get this done.)

**Comment by jskeet** [comment] 2018-01-15 18:04
> but I need to handle a situation where a single client makes multiple speech recognition requests simultaneously, so sharing one channel is an unavailable option.

What makes you think you can't perform multiple streaming operations in parallel on a single channel? I'd expect that to be fine.

In your example, you've commented out a lot of code in Call2 - do you see the memory increase both with and without that code? Are you seeing any exceptions?

**Comment by sg-blake** [comment] 2018-01-16 05:25
Thanks for the reply.

I thought a single channel could take only one streaming call, but after checking I understood that multiple streaming call processing is available, thanks for pointing it out.
However, if I ShutdownAsync() the channel it becomes no longer usable, but the memory used doesn’t get released. I’m suspicious that there’s a problem inside SpeechClient and gRPC modules.

The commented out block in Call2() is for writing config data and stream data, as you may already know.
This part doesn’t affect the memory leak situation.

`var stream = speech.StreamingRecognize();`
Memory leak occurs when this call is included, it doesn’t when not.

And no specific exceptions are seen.

**Comment by jskeet** [comment] 2018-01-16 08:23
I believe this is a problem in Grpc.Core, and I'll report it on the gRPC repo and link to it from here.

Here's a shorter example that demonstrates the problem:

```csharp
using Google.Apis.Auth.OAuth2;
using Google.Cloud.Speech.V1;
using Grpc.Auth;
using Grpc.Core;
using System;

public class Test
{
    public static void Main(string[] args)
    {
        GoogleCredential googleCredential = GoogleCredential.GetApplicationDefault();
        for (int i = 0; i < 100; ++i)
        {
            var channel = new Channel(SpeechClient.DefaultEndpoint.Host, googleCredential.ToChannelCredentials());
            var speech = SpeechClient.Create(channel);
            var stream = speech.StreamingRecognize();
            stream.WriteCompleteAsync().Wait();
            // stream.ResponseStream.MoveNext(System.Threading.CancellationToken.None).Wait();
            channel.ShutdownAsync().Wait();
            Console.WriteLine($"{i}: {GC.GetTotalMemory(true)}");
        }
    }
}
```

If the commented-out line is uncommented then:

- The memory leak goes away
- The shutdown occurs more rapidly too

So for the moment, you have two workarounds: reusing the same channel, or ensuring that you observe the end of the streaming call.

I'll close this issue now as I don't think there's anything else we could do in this client library, but hopefully the Grpc.Core library can be fixed to at least fix the leak. (Whether it can make shutdown quick without calling `MoveNext` I'm not sure.)

**Comment by jskeet** [comment] 2018-01-16 08:31
Reopened as now I'm seeing different behaviour even for the same code - this is very strange. I'll continue investigating.

**Comment by jskeet** [comment] 2018-01-16 08:44
Okay, closing again - the difference is in Grpc.Core 1.8.3, which makes this a lot worse. (I'll include that in the bug...)

**Closed by jskeet** 2018-01-16 08:44 UTC
Labels: api: speech, status: investigating, type: bug

**Comment by jskeet** [comment] 2018-01-16 08:54
Filed https://github.com/grpc/grpc/issues/14021

**Comment by sg-blake** [comment] 2018-01-16 09:02
For others who would search about this issue in the future,
I'll add my test results to this thread.
jskeet's MoveNext() solution works on Grpc.Core 1.6.1,
(which was default in Google's Speech sample code),
while 1.8.0, 1.8.3 still has the leak.

Thanks for the solution, jskeet. You saved my day :)

**Comment by jskeet** [comment] 2018-01-16 09:11
My pleasure :) Note that Grpc.Core 1.7.x seems to be okay as well, if you call `MoveNext()`. The leak in Grpc.Core 1.8.x is much more noticeable (at least on my machine) than the non-MoveNext leak in earlier versions - there are some figures in the linked issue.
