### ISSUE TITLE
Pub/Sub client: excessive timeout rate with default seetings.

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-dotnet#733] opened 2017-02-02 18:01 UTC
A user has come to the Pub/Sub team reporting a high rate of pull request time outs in F# environment. This was fixed by explicitly setting call timing parameter. Any ideas if this could be a systematic issue? Not an expert on the .NET environment here. 

Code that did *not* work:
```
            try
                    logger.info (eventX "pulling next message")
                    let! response = SubscriberClient.Create().PullAsync(subscription, returnImmediately = false, maxMessages = 1) |> Async.AwaitTask
```
Code that did work:
```
 let settings = SubscriberSettings.GetDefault()
                settings.PullSettings <- CallSettings.FromCallTiming(CallTiming.FromTimeout(TimeSpan.FromSeconds(90.)))
                let client = SubscriberClient.Create(settings = settings)
                try
                    logger.info (eventX "pulling next message")
                    let! response = client.PullAsync(subscription, returnImmediately = false, maxMessages = 1) |> Async.AwaitTask
```

**Comment by jskeet** [comment] 2017-02-02 18:34
Thanks for the feedback. The default settings are taken from [this configuration file](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub_gapic.yaml) - and all the other languages using the same codegen platform are likely to be hit in the same way.

The change you've suggested removes retries entirely though, and that doesn't sound like it's what we want (I expect). We should work out what the most appropriate settings are, then we can update the file appropriately.

// cc @chrisdunelm who works on the codegen and knows more about the timing configuration.

**Comment by baronfel** [comment] 2017-02-06 20:16
Hi @jskeet et all, I'm the developer that wrote the code in question. If there's any more environment data or general app architecture information I can provide that would be useful, please let me know and I'll help out how I can.

**Comment by jskeet** [comment] 2017-02-07 06:47
Can I check exactly what you were seeing? Thinking about this again, I suspect the problem was that retry config only actually gives 12 seconds per RPC, with a 1 minute total timeout and a short delay between RPCs - so it will basically end up trying 4 times, each only 12 seconds long. Does that tie in with what you were seeing? I can definitely suggest a change to this piece of the config. (It's slightly tricky as you wouldn't want such a long timeout if `returnImmediately` is true, probably...)

**Comment by baronfel** [comment] 2017-02-07 17:12
Let me give a little more code context and then provide some of the errors we were seeing.

The app in question is a fairly standard pull-process-(requeue|notify next queue) model, in the interests of injecting our dependencies we started by creating a single shared `PublisherClient` and `SubscriberClient` using the default settings, via the `Create()` methods on the respective classes.  These instances would be provided as parameters to function that use the client, like this polling function that generates a single message asynronously:

<details>
<summary>Poll function</summary>
```fsharp
    /// poll the given client for a single message and return it.
    /// in the case of no messages returned, or exceptions thrown by the underlying RPC call, log the error and retry
    let pollMessages (logger : Logger) (client : SubscriberClient) subscription =
        let rec loop () =
            async {
                try
                    logger.info (eventX "pulling next message")
                    let! response = client.PullAsync(subscription, returnImmediately = false, maxMessages = 1) |> Async.AwaitTask
                    if response.ReceivedMessages.Count = 1
                    then return response.ReceivedMessages.[0]
                    else return! loop ()
                with
                // if the error is a known GRPC exeception of code Unavailable or Timeout, it's not a real big problem, just try again
                | SingleAggregate(Unavailable) 
                | SingleAggregate(Timeout) as err ->
                    logger.verbose (eventX "encountered a normal operational event" >> setField "err" (string err))
                    return! loop () 
                // in unexpected cases, log at a higher level to trigger alerting and try again
                | exn ->
                    logger.warn (eventX "unhandled error pulling messages: {err}" >> setField "err" (string exn))
                    return! loop ()
            }
        loop ()
```
</details>

There's a counterpart that acks a message id given a client and a message id that looks like this:

<details>
<summary>ack function</summary>
```fsharp
    let ackMsg (logger : Logger) (client : SubscriberClient) (subscription : SubscriptionName) (message : ReceivedMessage) = 
        logger.info (eventX "acking message {id}" >> setField "id" message.Message.MessageId)
        async {
            let! resp = client.AcknowledgeAsync(subscription, Seq.singleton message.AckId)
            logger.info (eventX "acked message {id}" >> setField "id" message.Message.MessageId)
        }
```
</details>

What we found when we passed a single shared client as an argument like this is that as soon as we finished the first cycle of pull-ack-process-notify and began to pull the next message, we'd start logging a flood of errors abouty safe handles being closed:

<details>
<summary>underlying objectdisposedexception</summary>
```
unhandled error pulling messages: System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
   at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCallAsync(TRequest msg)
   at Grpc.Core.Calls.AsyncUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.PubSub.V1.Subscriber.SubscriberClient.PullAsync(PullRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__0(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
   at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCallAsync(TRequest msg)
   at Grpc.Core.Calls.AsyncUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.PubSub.V1.Subscriber.SubscriberClient.PullAsync(PullRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__0(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()<---
```
</details>

Having seen tons of those, we switched to the current 'New up a client every iteration' plan which led to this behavior, which I don't especially like because that means we create a new channel for every client that just gets torn down, which seems expensive and excessive.

So now on the 'New up a client every iteration' plan, the behavior we see with the 90 second time out is just a blocking of pulls entirely.  You can see that we log every time we loop to do the pull as sort of a heartbeat that some activity is happening, and what we'll see is a handful of days of consistent activity, and then a final heartbeat message and then no new message until we restart the application.

Does this provide any useful information?

**Comment by jskeet** [comment] 2017-02-07 17:20
Well it certainly makes it sound a lot more worrying :( It'll take me a little while to process all of that, but @jtattermusch should definitely be aware of the ObjectDisposedException - that sounds like it's either a gRPC bug, or some way in which we're using gRPC very incorrectly.

In the interests of getting to the bottom of this reasonably easily, are you able to reproduce the problem in a brief C# console app? (While I could stare at the F# for a long time, I suspect you'll be better at translating it to C# than I will.)

**Comment by baronfel** [comment] 2017-02-07 17:25
Sure, I can take a stab at it. It may take a few days due to other work constraints.

**Comment by jtattermusch** [comment] 2017-02-10 16:33
Filed a separate issue to investigate the ObjectDisposedException https://github.com/grpc/grpc/issues/9670. @baronfel  can you please provide some details about when you're seeing this?

**Comment by jskeet** [comment] 2017-06-21 09:19
@baronfel: Any update on the C# repro? Would like to look into this...

**Comment by jskeet** [comment] 2017-07-21 06:19
Reassigned to Chris as he's closer to PubSub than I am these days. Although without having heard anything since February, I'm tempted to close...

**Comment by jskeet** [comment] 2017-09-27 16:01
We're now 6 months later, and quite a bit has changed, including new versions of gRPC and the SimplePublisher/SimpleSubscriber classes designed for high-performance scenarios. Closing for now - we can reopen if we can reproduce it later.

**Closed by jskeet** 2017-09-27 16:01 UTC
Labels: Priority: P1, Type: Bug
