### ISSUE TITLE
Google Streaming Speech Recognition does not return responses

### ISSUE THREAD

**Issue by gkralj** [GoogleCloudPlatform/google-cloud-dotnet#1351] opened 2017-08-11 07:11 UTC
We followed [example ](https://cloud.google.com/speech/docs/streaming-recognize) on official Google page for performing Streaming Speech recognition on an Audio stram.

There is a problem, that sometimes for sent audio chunks we dont get any kind ( of recognized) responses back. In next line of code NOTHING is returned back from Google.

` Task printResponses = Task.Run(async () => ...`

Is that expected scenario and what should we assume the problem was?

Regards

**Comment by jskeet** [comment] 2017-08-11 07:21
Does the task ever complete? If it does complete, does it complete successfully, or with an exception?
You might want to try putting a try/catch block inside the async method, just to see if that reveals an error.

If this is streaming from a local file, are you able to share that file? It would be great to be able to reproduce the problem.

**Comment by gkralj** [comment] 2017-08-11 07:36
Thanks for quick reply. 

We are recording audio thorugh microphone and sending audio chunks directly to Google ( not through local file ). 

Weird thing is; we are receiving successful recognitions ( in printResponse ) and randomly not receiving
any kind of response in printResponse line (it is as if we are sending silence ). Code is the same as in example. And exeptions are not thrown/happening.

We have set recognition for Slovenian ( sl-SI ) language.

**Comment by jskeet** [comment] 2017-08-11 07:41
Could you try recording some sound to a file, and reproducing the problem that way? Basically, the more reliable the problem reproduction, the more likely it is that we'll be able to get to the bottom of it. (It may be a client library issue, or it may be a server API issue.)

Once you have a file, that gives us multiple options:

- We can send the file for immediate recognition
- We can stream the file *as if* we were recording straight from the microphone
- We can try using the same data from other platforms

**Comment by gkralj** [comment] 2017-08-11 08:01
Thanks for your reply

I understand what you want, and you want to reproduce it, but I really doubt that is the issue here. 
Actually when I say the same word many times, the word is usually recognized, but sometimes not (printResponse not called at all). 

So the actual problem here as I see it, why any kind of recognition is not displayed sometimes.

Here is the complete code. Problem is PRINT RESPONSE CALLED AT is not called.

`private static async Task<RecognizeResult> StreamingMicRecognizeAsync(
            string _language,
            int _seconds
        )
        {
            RecognizeResult recognizeResult = new RecognizeResult();
            NAudio.Wave.WaveInEvent waveIn = null;
            bool taskCanceled = false;

            try
            {
                var cancellationTokenSource = new CancellationTokenSource();
                var cancellationToken = cancellationTokenSource.Token;

                if (NAudio.Wave.WaveIn.DeviceCount < 1)
                {
                    recognizeResult.response = "No microphone!";
                    recognizeResult.success = false;
                    return recognizeResult;
                }
                var speech = SpeechClient.Create();
                var streamingCall = speech.StreamingRecognize();
                // Write the initial request with the config.
                await streamingCall.WriteAsync(
                    new StreamingRecognizeRequest()
                    {
                        StreamingConfig = new StreamingRecognitionConfig()
                        {
                            Config = new RecognitionConfig()
                            {
                                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                                SampleRateHertz = 16000,
                                LanguageCode = _language,
                            },
                            InterimResults = true,
                        }
                    });
                // Print responses as they arrive.
                Task printResponses = Task.Run(async () =>
                {
                    while (await streamingCall.ResponseStream.MoveNext(
                        default(CancellationToken)))
                    {
//PROBLEM HERE; Not called sometimes
                        System.Diagnostics.Debug.WriteLine("PRINT RESPONSE CALLED AT " + DateTime.Now.ToString());

                        if (!taskCanceled)
                        {
                            if (streamingCall.ResponseStream.Current.Error != null)
                            {
                                System.Diagnostics.Debug.WriteLine("ERROR CODE" + streamingCall.ResponseStream.Current.Error.Message);
                            }

                            foreach (var result in
                                    streamingCall.ResponseStream.Current.Results)
                            {
                                if (result.IsFinal)
                                {
                                    System.Diagnostics.Debug.WriteLine("***IS FINAL***");
                                    var finalResult = result.Alternatives.Last();
                                    recognizeResult.isFinal = true;
                                    recognizeResult.success = true;
                                    recognizeResult.response = string.Format("{0} ({1})", finalResult.Transcript, finalResult.Confidence);


                                    System.Diagnostics.Debug.WriteLine(
                                        string.Format("{0}:{1}", finalResult.Transcript, finalResult.Confidence)
                                        );

                                    // cancelling
                                    cancellationTokenSource.Cancel();
                                    taskCanceled = true;
                                }
                            }
                        }
                    }
                });
                // Read from the microphone and stream to API.
                object writeLock = new object();
                bool writeMore = true;
                waveIn = new NAudio.Wave.WaveInEvent();
                waveIn.DeviceNumber = 0;
                waveIn.WaveFormat = new NAudio.Wave.WaveFormat(16000, 1);
                waveIn.DataAvailable +=
                    (object sender, NAudio.Wave.WaveInEventArgs args) =>
                    {
                        System.Diagnostics.Debug.WriteLine("DATA AVAILABLE AT "+DateTime.Now.ToString());

                        lock (writeLock)
                        {
                            if (!writeMore) return;
                            streamingCall.WriteAsync(
                                new StreamingRecognizeRequest()
                                {
                                    AudioContent = Google.Protobuf.ByteString
                                        .CopyFrom(args.Buffer, 0, args.BytesRecorded)
                                }).Wait();
                        }
                    };
                waveIn.StartRecording();
                System.Diagnostics.Debug.WriteLine("Speak now.");

                await Task.Delay(TimeSpan.FromSeconds(_seconds), cancellationToken);

                // Stop recording and shut down.
                waveIn?.StopRecording();
                lock (writeLock) writeMore = false;
                await streamingCall.WriteCompleteAsync();
                await printResponses;
            }
            catch (System.Threading.Tasks.TaskCanceledException ex)
            {
                if (taskCanceled)
                {
                    //all ok actually, manually triggered
                    System.Diagnostics.Debug.WriteLine("***TASK CANCELED***");
                }
                else
                {
                    recognizeResult.success = false;
                    recognizeResult.response = ex.ToString();
                }
            }
            catch (Exception ex)
            {
                recognizeResult.success = false;
                recognizeResult.response = ex.ToString();
            }
            finally
            {
                //cleanup sources
                waveIn?.StopRecording();
            }

            return recognizeResult;
   }`

**Comment by jskeet** [comment] 2017-08-11 08:06
> I understand what you want, and you want to reproduce it, but I really doubt that is the issue here.

The point is that if you can provide a sound file, I will be in a *much* better position to reproduce it reliably, and the example will be much more self-contained, and simpler too.

Is there any reason you *don't* want to do this via a file? Have you tried and found that it can't be reproduced via a file? If you provide the file - just record the microphone at the same time as you run the code - I'm happy to try to adapt your code to *use* the file.

**Comment by gkralj** [comment] 2017-08-11 09:13
Here are sharable links from Google drive.
Although I could not manage to make it work with sample.


It means '**število**' or number in english.
https://drive.google.com/open?id=0B_UDmUofR3boanNxdWxwMFBZdjA
https://drive.google.com/open?id=0B_UDmUofR3boQWYxR2FBUklid1U
https://drive.google.com/open?id=0B_UDmUofR3bob0RMMXQ4UXktaUE
https://drive.google.com/open?id=0B_UDmUofR3boY1ViUVFoSERFZzQ
https://drive.google.com/open?id=0B_UDmUofR3boNmlIRnVlQ251a3c

**Comment by jskeet** [comment] 2017-08-11 09:23
Thanks for the files. When you say you "could not manage to make it work with sample" what do you mean, exactly? You couldn't get speech recognition to work with that file format, or you couldn't reproduce the problem?

If it's a file format issue, an alternative would be to use your existing microphone code, but just write to a file at the same time that you call `streamingCall.WriteAsync`. That way we'd have the *exact* same bytes that you're currently seeing cause a problem, which would be ideal.

Let me know if you're happy to provide files created that way - if it's too much hassle, I'll try to convert the files you've provided instead.

**Comment by gkralj** [comment] 2017-08-11 09:25
I mean, I have recorded files with Audacity ( mono, 16000hz, pcm )
I run sample with file upload, but I have not received any transcripts nor any errors.

**Comment by gkralj** [comment] 2017-08-11 09:29
I will try to make files by your preposition.

**Comment by jskeet** [comment] 2017-08-11 09:30
That would be great, thanks. Listening to the files you provided, they're currently pretty quiet - it's possible that that's why you're not seeing any responses. I'll investigate that myself while you're creating the files to investigate the streaming issue. (There may be two problems here, or it may just be a volume problem.)

**Comment by jskeet** [comment] 2017-08-11 10:50
I've just tried your first "število" example file, and:

- I don't think the API supports WAV, so I used Audacity to convert it to LinearPCM
- There were still no results, so I amplified the file
- That then resulted in "delo" - not accurate, but it's a result
- I recorded saying "število" myself with my microphone, and that was fine

So I suspect that this is a problem of the audio level/quality. Are you able to increase your microphone gain?

**Comment by jskeet** [comment] 2017-08-16 10:17
Any update on this? Given my analysis, I'll close this in a few days unless you can confirm it's still a problem even with louder input (in which case obviously I'll investigate further).

**Comment by gkralj** [comment] 2017-08-17 09:02
Sorry for a really late reply and not providing you the problematic sample.
Yes, we are still experiencing the issue for not getting any transcripts for some audio sample ( maybe I haven't mentioned yet, but sometimes we ARE getting transcripts but are NOT final).

Right now, I am trying in (waveIn.DataAvailable) handler to create actual audio file ( for later history ), but I haven't finished that yet ( Btw, how would you create such file with streaming speech reacognition, with MemoryStream ? ).

**Comment by jskeet** [comment] 2017-08-17 09:19
In order to dump the data to a file, all you need to do is open a `FileStream` and then where you're calling this:

```csharp
streamingCall.WriteAsync(
    new StreamingRecognizeRequest()
    {
        AudioContent = Google.Protobuf.ByteString.CopyFrom(args.Buffer, 0, args.BytesRecorded)
     })
```

... you'd also write to the stream:

```csharp
stream.Write(args.Buffer, 0, args.BytesRecorded);
```

**Comment by gkralj** [comment] 2017-08-18 13:26
hello.
I turned out, with different microphone/volume settings and latest packages things are working good!

I have managed to implement file save when streaming. All are recognized ( I get transcripts back ).
I have tried below files:

https://drive.google.com/open?id=0B_UDmUofR3boUTY0RjNHUFB4QWs
https://drive.google.com/open?id=0B_UDmUofR3boWGJzZ0V0WGNETFE
https://drive.google.com/open?id=0B_UDmUofR3boMEdVdjdLZlRnRnM
https://drive.google.com/open?id=0B_UDmUofR3boMkdhbUN2MHBMOXc
https://drive.google.com/open?id=0B_UDmUofR3boWkhKSlJfTy1DZms
https://drive.google.com/open?id=0B_UDmUofR3boNU12c1BRb2s1Nk0
https://drive.google.com/open?id=0B_UDmUofR3boaWJzMTE1aDd2U3c
https://drive.google.com/open?id=0B_UDmUofR3bocFhHbGFKNFJOUGs
https://drive.google.com/open?id=0B_UDmUofR3bod2czSE54aW9ib28
https://drive.google.com/open?id=0B_UDmUofR3boVlROWDlzYUtNems
https://drive.google.com/open?id=0B_UDmUofR3boM2s4TmdaZ045RnM
https://drive.google.com/open?id=0B_UDmUofR3boY3FqOUdpVmJoSVE
https://drive.google.com/open?id=0B_UDmUofR3bobzRkbmsybkp4QjA
https://drive.google.com/open?id=0B_UDmUofR3boNE9SVEViS21taFk
https://drive.google.com/open?id=0B_UDmUofR3boMzB5OW1FZkJoU28
https://drive.google.com/open?id=0B_UDmUofR3boSEVCZENSZFNlSDQ
https://drive.google.com/open?id=0B_UDmUofR3bobmVwZ0JfNnpyNGM

**Comment by jskeet** [comment] 2017-08-18 13:28
Hooray - I'm glad it worked for you :) I'll close this issue now.

**Closed by jskeet** 2017-08-18 13:28 UTC
Labels: Priority: P1, Type: Bug
