### ISSUE TITLE
"The Application Default Credentials are not available" error when configuring logging

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/google-cloud-dotnet#1970] opened 2018-03-08 11:32 UTC
I configure an ASP.NET Core web app to use logging using the code below in Program.cs: 

public static IWebHost BuildWebHost(string[] args) {
...
 return WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((ctx, logging) =>
                logging.AddProvider(GoogleLoggerProvider.Create("project-id")))
}

I run it locally and everything works. When I deploy to App Engine Flex using "gcloud app deploy", I get the following error during deployment:

ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
Unhandled Exception: System.InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
   at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.<CreateDefaultCredentialAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Api.Gax.Grpc.ChannelPool.<CreateChannelCredentialsUncached>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions(Task task)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint)
   at Google.Cloud.Diagnostics.AspNetCore.GoogleLoggerProvider.Create(LogTarget logTarget, LoggerOptions options, LoggingServiceV2Client client)
   at GoogleHomeAspNetCoreDemoServer.Program.<>c.<BuildWebHost>b__5_0(WebHostBuilderContext ctx, ILoggingBuilder logging) in C:\dev\local\GoogleHomeAspNetCoreDemo\GoogleHomeAspNetCoreDemoServer\Program.cs:line 39

The error is clear but not clear at all what I need to do on App Engine Flex. I surely cannot set environment variables in App Engine Flex.

**Comment by chrisdunelm** [comment] 2018-03-08 11:37
This looks very similar to #1394. Can you check which version of Google.Apis.Auth you're using? If it's less than v1.32.2, please upgrade.

**Comment by meteatamel** [comment] 2018-03-08 11:43
I'm not using Google.Apis.Auth at all. At least I don't see it in my dependencies. I'm using Google.Cloud.Diagnostics.AspNetCore (2.0.0)

**Comment by chrisdunelm** [comment] 2018-03-08 11:48
`Google.Cloud.Diagnostics.AspNetCore` 2.0.0 ultimately has a dependency on `Google.Apis.Auth` v1.27.1

If you add a dependency in the project to `Google.Api.Gax.Grpc` v2.3.0 (the latest), then this will also bring in `Google.Apis.Auth` v1.32.2, which should have a fix for this problem.

**Comment by meteatamel** [comment] 2018-03-08 12:03
Sure, I can try that but why do I need to pull in these dependencies manually? I have Google.Cloud.Diagnostics.AspNetCore 2.0.0 dependency but that didn't pull in Google.Api.Auth. Another dependency of mine Grpc.Auth 1.8.3 pulled in Google.Apis.Auth 1.31.1. Is that why? If so, how would people know what library needs what version of dependencies to work correctly?

**Comment by chrisdunelm** [comment] 2018-03-08 12:06
`Google.Cloud.Diagnostics.AspNetCore` *does* pull in `Google.Apis.Auth`, but an older version.
We're just about to do a new release of all libraries to bring in the latest versions of all the support libraries, including `Google.Api.Gax.Grpc` and `Google.Apis.Auth`. Once this new release is pushed for all packages, manually adding up-to-date dependencies won't be required.

**Comment by jskeet** [comment] 2018-03-08 12:12
Just to give more clarity: you can always explicitly add a dependency to a more recent version of a library, even if you've got an older version implicitly present. Basically the bug fix is in Google.Apis.Auth, so that's the library you should update to get the fix. Libraries that depend on a fixed library will very often lag behind, but you can always force an update by including the dependency explicitly.

If it's still unclear, I'm happy to have a VC :)

**Comment by meteatamel** [comment] 2018-03-08 13:11
Ok, I'll update Google.Apis.Auth then. 

FYI, this is the dependency graph I see in Visual Studio. You can see that Grpc.Auth pulls in Google.Apis.Auth but Google.Cloud.Diagnostics.AspNetCore does not...At least according to the Visual Studio.
 
![capture](https://user-images.githubusercontent.com/1177542/37152655-03f20544-22d2-11e8-90b7-fffe68231f8a.PNG)

**Comment by jskeet** [comment] 2018-03-08 13:35
Google.Cloud.Diagnostics.AspNetCore depends on Google.Cloud.Diagnostics.Common, which in turn depends on Google.Cloud.Logging.V2, which in turn depends on Google.Api.Gax.Grpc, which in turn depends on Google.Apis.Auth. I expect if you expand the entries that way, VS will show you them :)

**Comment by meteatamel** [comment] 2018-03-09 10:18
@jskeet Of course, you were right :-) Updating Google.Apis.Auth to the latest version worked. Thanks for the help!

**Comment by jskeet** [comment] 2018-03-09 10:25
Phew - glad it worked :)

Closing this issue now. (As new libraries are released with updated dependencies, hopefully fewer people will run into this.)

**Closed by jskeet** 2018-03-09 10:25 UTC

**Comment by aseemgautam** [comment] 2018-03-23 06:26
I have run this error on OS X 10.13.3. Environment variable is added to `.bash_profile` - 
`export GOOGLE_APPLICATION_CREDENTIALS="/Users/aseemgautam/somepath"`. Doing an `echo $GOOGLE_APPLICATION_CREDENTIALS` does return its value.

`Google.Cloud.Diagnostics.AspNetCore` was not referring to latest version, so I went ahead and added nuget packages - `Google.api.auth` & `Grpc.core`

Here is the dependency graph -

<img width="485" alt="screen shot 2018-03-23 at 11 54 04 am" src="https://user-images.githubusercontent.com/3583020/37814637-f89248d8-2e90-11e8-9a20-d4d771e33721.png">

It still gives the error - System.InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials.

Have I missed anything?

**Comment by jskeet** [comment] 2018-03-23 06:34
How are you running the code? Are you sure the environment variable is available in *that* context? If you log `System.Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS")` does that show the value you'd expect? I think it would be best to raise a separate issue with more details, as this is a different situation to the one being discussed in previous comments, where the code is running on Compute Engine so shouldn't require the environment variable at all. That issue is fixed (we believe) so let's help you in another issue.

**Comment by aseemgautam** [comment] 2018-03-23 06:43
@jskeet Yeah, you're right `System.Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS")` is null. This seems to be the real issue. Thanks

**Comment by aseemgautam** [comment] 2018-03-23 07:48
Tried quite a lot of things, `environment.plist` file etc. The only thing that seem to work is to open `Visual Studio` from terminal. `open -a "Visual Studio.app"`. It's then able to read environment variables from `.bash_profile`.

**Comment by codeapin** [comment] 2018-07-06 06:32
I am having the same issue too... System.Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS") is null.
I've downloaded the credentials and set it to the environment variable

**Comment by jskeet** [comment] 2018-07-06 06:34
@codeapin

> I've downloaded the credentials and set it to the environment variable

Could you say *exactly* how you've set the environment variable? We don't have any context for what operating system you're using, how you've set the variable, how you're running your code etc. To be clear, if `GetEnvironmentVariable` returns null, then the problem is in the way you've set the environment variable - that's what we'll be looking to sort out.

**Comment by codeapin** [comment] 2018-07-06 06:42
I am using windows 10, I've set it through System Properties > Environment Variables

**Comment by jskeet** [comment] 2018-07-06 06:43
@codeapin: And how are you running the code? If you set it in the system properties before you either started a command prompt where you're running the code, or before launching Visual Studio, that could well be the problem.

**Comment by codeapin** [comment] 2018-07-06 07:33
@jskeet : I've set it after launching visual studio, and then I restart it and It works, thank you

**Comment by akhan700010** [comment] 2019-04-09 15:52
> Google.Cloud.Diagnostics.AspNetCore depends on Google.Cloud.Diagnostics.Common, which in turn depends on Google.Cloud.Logging.V2, which in turn depends on Google.Api.Gax.Grpc, which in turn depends on Google.Apis.Auth. I expect if you expand the entries that way, VS will show you them :) (I've just tried that myself, and it worked as I expected.)



> How are you running the code? Are you sure the environment variable is available in _that_ context? If you log `System.Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS")` does that show the value you'd expect? I think it would be best to raise a separate issue with more details, as this is a different situation to the one being discussed in previous comments, where the code is running on Compute Engine so shouldn't require the environment variable at all. That issue is fixed (we believe) so let's help you in another issue.

I just to thank you from the bottom of my heart, i figured it out thanks to you T_T
