### ISSUE TITLE
Datastore Credentials

### ISSUE THREAD

**Issue by samgithub-duplicate** [GoogleCloudPlatform/google-cloud-dotnet#2191] opened 2018-05-29 19:54 UTC
Is there a way to explicitly pass credentials to DatastoreDB (instead of using GOOGLE_APPLICATION_CREDENTIALS from the environment)  

We are working in a secure environment where the json file will be stored physically encrypted on the server.  It will be supplied to the app which will decrypt it and use it.  The storage client provides a way to pass credentials in

**var credential = GoogleCredential.GetApplicationDefault();
    var storage = StorageClient.Create(credential);**

(see https://cloud.google.com/docs/authentication/production )

**Comment by jskeet** [comment] 2018-05-31 16:28
Closing this as a duplicate of #1941.

**Closed by jskeet** 2018-05-31 16:28 UTC
