### ISSUE TITLE
metadataClient.GetMetadataAsync() fails when it should succeed.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1568] opened 2017-10-20 04:20 UTC
Here's the code:
```cs
            var metadataClient = Google.Cloud.Metadata.V1.MetadataClient.Create();
            try
            {
                var result = await metadataClient.GetMetadataAsync(
                    "instance/network-interfaces/0/access-configs/0/external-ip");
                return result.Content.ToString();
            }
            catch (System.Net.Http.HttpRequestException e)
            {
                _logger.LogError(0, e, "I must not be running on App Engine.");
            }
            // Try one more time with the full url and an old-fashioned HTTP connection.
            try 
            {
                var http = new HttpClient();
                http.DefaultRequestHeaders.Add("Metadata-Flavor", new [] {"Google"});
                return await http.GetStringAsync(
                    "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip");
            }
            catch (System.Net.Http.HttpRequestException e)
            {
                _logger.LogError(1, e, "I must really not be running on App Engine.");
            }
            return null;
```

When running on a Linux Google Compute Engine instance, the call to metadataClient.GetMetadataAsync() succeeds.

When running on a *Windows* Google Compute Engine instance, the call to metadataClient.GetMetadataAsync() fails, but the `HttpClient` request to the same url succeeds.

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Google.Apis.Http.ConfigurableMessageHandler.<SendAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Metadata.V1.MetadataClientImpl.<RequestMetadataAsync>d__24.MoveNext() in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Metadata.V1\Google.Cloud.Metadata.V1\MetadataClientImpl.cs:line 224
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Metadata.V1.MetadataClientImpl.<GetMetadataCoreAsync>d__40.MoveNext() in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Metadata.V1\Google.Cloud.Metadata.V1\MetadataClientImpl.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Metadata.Startup.<GetMyGoogleCloudIpAddressAsync>d__3.MoveNext() in T:\src\github\dotnet-docs-samples\appengine\flexible\Metadata\Startup.cs:line 73
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2773.1155ms 200 text/html
```

The full sample code is here:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/556ca805ed96f926b18240da84d46ad9c00f1ece/appengine/flexible/Metadata

**Comment by jskeet** [comment] 2017-10-20 06:27
@ivannaranjo @evildour @chrisdunelm - you all know more about the metadata side of things than I do. Any ideas?

**Comment by evildour** [comment] 2017-10-20 15:55
No ideas yet, but I'll see if I can reproduce it. In the meantime, @SurferJeffAtGoogle, can you try changing your manual call to use a host of "metadata" rather than "metadata.google.internal" and see if that still succeeds? That is what the library uses so I'm curious to know if there's been a change what is accepted on the Windows VMs. Also, can you verify that your VM does NOT have the METADATA_EMULATOR_HOST environment variable set? If that is present, we will use that host instead of the default. Thanks.

**Comment by evildour** [comment] 2017-10-20 17:17
I can't reproduce the issue using a Windows Server 2016 instance. Can you provide some more details about the Windows instance where this is failing for you?

**Comment by SurferJeffAtGoogle** [comment] 2017-11-03 16:50
The environment variable METADATA_EMULATOR_HOST is not set.
When I change the manual call to use a host of "metadata" rather than "metadata.google.internal", then the manual call fails with:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server name or address could not be resolved
```

**Comment by evildour** [comment] 2017-11-03 18:10
Ok this seems like the problem. So normally both 'metadata' and 'metadata.google.internal' are mapped to 169.254.169.254, the address of the metadata server. This can be seen in the hosts file of the Compute Engine Windows Server 2016 VM (C:\Windows\System32\drivers\etc\hosts):
`# Google Compute Engine metadata server
    169.254.169.254    metadata.google.internal metadata`

How is your container setup such that 'metadata.google.internal' is mapped to 169.254.169.254 on the host machine, but 'metadata' is not?

Perhaps the metadata library should not make the assumption about any host mappings and should talk to 169.254.169.254 directly.

**Comment by evildour** [comment] 2017-11-03 18:22
By the way, as a quick workaround, you should be able to set `METADATA_EMULATOR_HOST` to `metadata.google.internal`

**Comment by jskeet** [comment] 2017-12-01 09:12
I suspect this may have the same root cause as #1394. I'll try to investigate them at the same time.

**Comment by jskeet** [comment] 2017-12-06 15:04
Closing for now having added this to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/BACKLOG.md)

**Closed by jskeet** 2017-12-06 15:04 UTC
