### ISSUE TITLE
New MVC App + CloudTrace.Initialize() yields exception.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/google-cloud-dotnet#1040] opened 2017-05-12 22:07 UTC
I created a new MVC web app.  Added the dependency Google.Cloud.Diagnostics.AspNet.  Then added a call to CloudTrace.Initialize(), and I get this exception when I try to run the application:

```
Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Here are the nuget packages pulled in by the app:
```
PM> get-package | select id, version

Id                                                 Version     
--                                                 -------     
Antlr                                              3.4.1.9004  
bootstrap                                          3.0.0       
Google.Api.CommonProtos                            1.0.0       
Google.Api.Gax                                     1.0.1       
Google.Api.Gax.Grpc                                1.0.1       
Google.Apis                                        1.24.1      
Google.Apis.Auth                                   1.24.1      
Google.Apis.Core                                   1.24.1      
Google.Cloud.Diagnostics.AspNet                    1.0.0-beta09
Google.Cloud.Diagnostics.Common                    1.0.0-beta01
Google.Cloud.ErrorReporting.V1Beta1                1.0.0-beta05
Google.Cloud.Logging.Type                          1.0.0       
Google.Cloud.Logging.V2                            1.0.0       
Google.Cloud.Trace.V1                              1.0.0-beta05
Google.Protobuf                                    3.2.0       
Grpc.Auth                                          1.2.2       
Grpc.Core                                          1.2.2       
jQuery                                             1.10.2      
jQuery.Validation                                  1.11.1      
Microsoft.AspNet.Mvc                               5.2.3       
Microsoft.AspNet.Razor                             3.2.3       
Microsoft.AspNet.Web.Optimization                  1.1.3       
Microsoft.AspNet.WebApi.Client                     5.2.3       
Microsoft.AspNet.WebApi.Core                       5.2.3       
Microsoft.AspNet.WebPages                          3.2.3       
Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.0       
Microsoft.jQuery.Unobtrusive.Validation            3.2.3       
Microsoft.Net.Compilers                            1.0.0       
Microsoft.Web.Infrastructure                       1.0.0       
Modernizr                                          2.6.2       
Newtonsoft.Json                                    10.0.1      
Respond                                            1.2.0       
System.Collections.Immutable                       1.3.1       
System.Interactive.Async                           3.1.1       
System.Net.Http                                    4.0.0       
WebGrease                                          1.5.2       
Zlib.Portable.Signed                               1.11.0      
```

Here's the code I added:
```
    public class MvcApplication : System.Web.HttpApplication
    {
        //
        // Summary:
        //     Executes custom initialization code after all event handler modules have been
        //     added.
        public override void Init()
        {
            base.Init();
            CloudTrace.Initialize(this, "surferjeff-phoenix");
        }
```

The source code can be found here:
https://github.com/SurferJeffAtGoogle/csharp-docs-samples/tree/40f6be97cc70a281a4f1ff69a9fd95fc6dc74148/trace/api

**Comment by iantalarico** [comment] 2017-05-12 22:43
I was able to repo the issue thanks for the detailed summary.

I'm having a hard time figuring our where "System.Collections.Immutable 1.2.1" is coming from.

I will dig into this more Monday morning.

**Comment by evildour** [comment] 2017-05-13 05:51
`ImmutableStack<T>` is used in the `SimpleManagedTracer` (see [here](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/Trace/SimpleManagedTracer.cs#L269)) because, with the help of the `ExecutionContext`'s copy-on-write behavior when entering new async contexts, it can be "forked" and create a logical tree of trace spans as async methods are entered or child threads are spawned.

@SurferJeffAtGoogle is the issue that the dependency is there at all, or that there is a versioning problem? If the former, it would actually be pretty simple to remove the dependency. There is not much to an immutable stack so it could easily be hand written, but it's possible something else would need this dependency in the future.

**Comment by iantalarico** [comment] 2017-05-15 15:26
I think this is a versioning issue we requires "System.Collections.Immutable 1.3.1" as does @SurferJeffAtGoogle's code.  I think somewhere along the line "System.Collections.Immutable 1.2.1" is getting mixed in.

**Comment by jskeet** [comment] 2017-05-15 15:28
I'll try to hunt down the dependency root...

**Comment by jskeet** [comment] 2017-05-15 16:15
Hmm. I can't reproduce the problem - the app opens for me, both when debugging and not (using VS2015).

I noticed that the web.config has a binding redirect, but only up to version 1.1.36:

```xml
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.36.0" newVersion="1.1.36.0" />
      </dependentAssembly>
```

**Comment by iantalarico** [comment] 2017-05-15 22:14
I think I see the issue but am unsure of how to fix it.

It looks like the System.Collections.Immutable is from Microsoft.Net.Compilers.1.0.0 (see 1) while  Google.Cloud.Diagnostics.Common references the nuget package System.Collections.Immutable  (see 2) 

1. ...\csharp-docs-samples\trace\api\packages\Microsoft.Net.Compilers.1.0.0\tools\System.Collections.Immutable.dll
2. ...\csharp-docs-samples\trace\api\packages\System.Collections.Immutable.1.3.1\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll

**Comment by jskeet** [comment] 2017-05-16 06:09
That should all be fine - I'd expect it to just take the highest version.

**Comment by evildour** [comment] 2017-05-16 13:50
I just tried to reproduce it and I thought I couldn't reproduce this either at first, but I think something a bit odd is going on, as if there's an attempt to create a `SimpleManagedTracer` which is silently failing perhaps (but turning on first-chance exceptions doesn't show anything in the debugger). The reason I say this is because looking at the loaded modules view in VS shows that System.Collections.Immutable is not loaded. When I remove the binding redirect, it is loaded. I used the fusion log viewer to see what was happening when trying to load the dependency and here is the log when the binding redirect is present:

```
*** Assembly Binder Log Entry  (5/16/2017 @ 9:34:07 AM) ***

The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\IIS Express\iisexpress.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/mdour/Desktop/csharp-docs-samples/trace/api/TraceMVC/
LOG: Initial PrivatePath = C:\Users\mdour\Desktop\csharp-docs-samples\trace\api\TraceMVC\bin
LOG: Dynamic Base = C:\Users\mdour\AppData\Local\Temp\Temporary ASP.NET Files\vs\f359963d
LOG: Cache Base = C:\Users\mdour\AppData\Local\Temp\Temporary ASP.NET Files\vs\f359963d
LOG: AppName = 1ada901
Calling assembly : Google.Cloud.Diagnostics.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\mdour\Desktop\csharp-docs-samples\trace\api\TraceMVC\web.config
LOG: Using host configuration file: C:\Users\mdour\Documents\IISExpress\config\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/mdour/AppData/Local/Temp/Temporary ASP.NET Files/vs/f359963d/1ada901/System.Collections.Immutable.DLL.
LOG: Attempting download of new URL file:///C:/Users/mdour/AppData/Local/Temp/Temporary ASP.NET Files/vs/f359963d/1ada901/System.Collections.Immutable/System.Collections.Immutable.DLL.
LOG: Attempting download of new URL file:///C:/Users/mdour/Desktop/csharp-docs-samples/trace/api/TraceMVC/bin/System.Collections.Immutable.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Users\mdour\Desktop\csharp-docs-samples\trace\api\TraceMVC\bin\System.Collections.Immutable.dll
LOG: Entering download cache setup phase.
LOG: Assembly Name is: System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: The assembly reference did not match the assembly definition found.
ERR: Setup failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

Here is what it looks like without the binding redirect:
```
*** Assembly Binder Log Entry  (5/16/2017 @ 9:41:00 AM) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\IIS Express\iisexpress.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Collections.Immutable
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: System.Collections.Immutable | Domain ID: 2
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/Users/mdour/Desktop/csharp-docs-samples/trace/api/TraceMVC/
LOG: Initial PrivatePath = C:\Users\mdour\Desktop\csharp-docs-samples\trace\api\TraceMVC\bin
LOG: Dynamic Base = C:\Users\mdour\AppData\Local\Temp\Temporary ASP.NET Files\vs\f359963d
LOG: Cache Base = C:\Users\mdour\AppData\Local\Temp\Temporary ASP.NET Files\vs\f359963d
LOG: AppName = 1ada901
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\mdour\Desktop\csharp-docs-samples\trace\api\TraceMVC\web.config
LOG: Using host configuration file: C:\Users\mdour\Documents\IISExpress\config\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/mdour/AppData/Local/Temp/Temporary ASP.NET Files/vs/f359963d/1ada901/System.Collections.Immutable.DLL.
LOG: Attempting download of new URL file:///C:/Users/mdour/AppData/Local/Temp/Temporary ASP.NET Files/vs/f359963d/1ada901/System.Collections.Immutable/System.Collections.Immutable.DLL.
LOG: Attempting download of new URL file:///C:/Users/mdour/Desktop/csharp-docs-samples/trace/api/TraceMVC/bin/System.Collections.Immutable.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Users\mdour\Desktop\csharp-docs-samples\trace\api\TraceMVC\bin\System.Collections.Immutable.dll
LOG: Entering download cache setup phase.
LOG: Assembly Name is: System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: A partially-specified assembly bind succeeded from the application directory. Need to re-apply policy.
LOG: Using application configuration file: C:\Users\mdour\Desktop\csharp-docs-samples\trace\api\TraceMVC\web.config
LOG: Using host configuration file: C:\Users\mdour\Documents\IISExpress\config\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Binding succeeds. Returns assembly from C:\Users\mdour\AppData\Local\Temp\Temporary ASP.NET Files\vs\f359963d\1ada901\assembly\dl3\6cf9c55d\007d72a5_25aad001\System.Collections.Immutable.dll.
LOG: Assembly is loaded in default load context.
```

In both cases, the app opens for me just fine.

**Comment by jskeet** [comment] 2017-05-16 13:52
Right - removing that binding redirect seems like a good first port of call.

@SurferJeffAtGoogle: Did you change the assembly binding redirects manually at all? Was this a genuine completely-fresh project? Is this VS2015?

**Comment by evildour** [comment] 2017-05-16 13:59
Oh no, I was mistaken. There are two log entries for `System.Collections.Immutable` running without the binding redirect. The 2nd one is the same as the original failure and shows the calling assembly is `Google.Cloud.Diagnostics.Common`. So it looks like the difference is that with the binding redirect, version `1.1.36.0` doesn't load (or even attempt to load), but without the binding redirect, it loads successfully.

**Comment by evildour** [comment] 2017-05-16 14:14
Ok, so now I can pretty consistently reproduce the issue if I put this line before the `CloudTrace.Initialize` call:
```csharp
BeginRequest += (object sender, EventArgs e) => { Thread.Sleep(1000); };
```
Maybe it has something to do with rate limiting perhaps? In any case, removing the binding redirect does not fix the issue.

**Comment by jskeet** [comment] 2017-05-16 14:21
Excellent, I can now reproduce the problem as well.

**Comment by jskeet** [comment] 2017-05-16 14:24
I'm now trying to reproduce by starting with a new MVC project (no auth) and adding one dependency at a time...

**Comment by jskeet** [comment] 2017-05-16 14:24
On project creation, we get redirect bindings of:

```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.5.2.14234" newVersion="1.5.2.14234" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by jskeet** [comment] 2017-05-16 14:35
Adding just `Google.Cloud.Diagnostics.AspNet` added the other redirections, including for System.Collections.Immutable to version 1.1.36. Still investigating...

**Comment by jskeet** [comment] 2017-05-16 14:42
Looks like this is a dupe of these:

- https://github.com/dotnet/roslyn/issues/12255
- https://github.com/aspnet/EntityFramework/issues/6220

Experimenting with fixes... it does strike me that if we could avoid the dependency on `System.Collections.Immutable`, that would be useful.

**Comment by jskeet** [comment] 2017-05-16 14:46
Okay, I have a workaround, at least - just update the `Microsoft.CodeDom.Providers.DotNetCompilerPlatfrm` dependency to v1.0.4 in "Manage NuGet packages". That seems to fix the problem - for now. I don't know whether it's just because the versions happen to be in alignment though.

**Comment by evildour** [comment] 2017-05-16 14:51
Yeah, that fixed it for me too. Ok, I will implement a custom immutable stack so we don't need this dependency anymore.

**Comment by iantalarico** [comment] 2017-05-16 14:58
@jskeet @evildour Thanks for looking into this!

**Comment by SurferJeffAtGoogle** [comment] 2017-05-16 16:10
> @SurferJeffAtGoogle: Did you change the assembly binding redirects manually at all? Was this a genuine completely-fresh project? Is this VS2015?

I didn't change assembly bindings at all.  It was a completely fresh project in vs2015.

**Closed** 2017-05-16 16:25 UTC
