### ISSUE TITLE
firestore nuget added to mvc project gives manifest error

### ISSUE THREAD

**Issue by babduljameel** [GoogleCloudPlatform/google-cloud-dotnet#2158] opened 2018-05-21 09:55 UTC
Hi 
I tried to add google.cloud.firestore nuget library to my mvc C# project. I get below error while running the project

An exception of type 'System.BadImageFormatException' occurred in mscorlib.dll but was not handled in user code

Additional information: Could not load file or assembly 'file:///[bin_path]\bin\grpc_csharp_ext.x64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

**Comment by jskeet** [comment] 2018-05-21 09:57
Please could you give more details about *exactly* what your project looks like? In particular:

- Which version of .NET are you targeting?
- Which version of ASP.NET are you using?
- Do you have anything else "interesting" about your project configuration?

Those should make it much easier to reproduce the problem.

**Comment by babduljameel** [comment] 2018-05-21 10:01
Hello,
I am using .NET 4.5.1 version, The project is created using ASP.NET 4.5 (MVC). No other specific configurations in my project.
I tried to add these nuget package to saperate solution, I am able to run and upload the data to firestore, but when I am trying to integrate the solution to my project the project run fails.
I have added the nuget to main solution as well.

**Comment by jskeet** [comment] 2018-05-21 10:11
Could you say excatly what you mean by "trying to integrate the solution to my project"? I'm unclear about which projects you have in your solution, and which projects have the Firestore NuGet package as a dependency.

You may want to try adding Grpc.Core as a direct dependency in your ASP.NET project - there's an issue with transitive dependencies on Grpc.Core that could exhibit behaviour like this.

**Comment by babduljameel** [comment] 2018-05-21 10:19
I have a solution name firebaseMigation which is responsible for all firebase cRUD opeations, I am trying to use it in my main solution UI.proj, after adding the reference firebaseMigration to UI.Proj I get this error.

how to add the direct dependency of Grpc.Core, I have this package already installed. Thanks for the help

**Comment by jskeet** [comment] 2018-05-21 10:29
It sounds like you're talking about *projects* rather than *solutions*. A solution is a collection of projects, and can't include a reference in its right.

If you only have a reference to Firestore in the FirebaseMigration project, please add a dependency to the Grpc.Core NuGet package in your UI project. Just use NuGet to add the dependency. You'll already have it as an indirect dependency, but you need it to be a direct dependency.

I'll see if I can reproduce the problem based on what you've said so far.

**Comment by babduljameel** [comment] 2018-05-21 10:30
I have added nuget package in both the solution (sorry for the words)

**Comment by jskeet** [comment] 2018-05-21 10:31
Again, I think you mean *project* rather than *solution*. Is that right? I'm double-checking because both words have very specific meanings in Visual Studio, but they *are* different. Am I right in saying you have a single *solution* (one ".sln" file) but multiple *projects* (multiple ".csproj" files)?

**Comment by babduljameel** [comment] 2018-05-21 10:32
yes your are right

**Comment by jskeet** [comment] 2018-05-21 10:53
I've tried to reproduce this, and failed. Here's what I've done:

- Open Visual Studio 2017 Community Edition
- Create a new solution ("Issue2158")
- Add a desktop class library project ("ClassLibrary") targeting .NET 4.5.1
- Add an ASP.NET MVC project ("WebApplication") targeting .NET 4.5.1
- Add a reference from WebApplication to ClassLibrary
- Add Google.Cloud.Firestore.V1 version 1.0.0-beta03 to ClassLibrary
- Add a new method in the class library Class1.cs called "MakeTestCall" returning a string
- Change `HomeController.About` to set the message to `Class1.MakeTestCall()`

Here's the content of `Class1.MakeTestCall()`:

```csharp
public static string MakeTestCall()
{
    var db = FirestoreDb.Create(...); // My project ID here
    // Note that this is a horrible abuse of an async method, but it's enough to
    // check that gRPC is being loaded correctly
    var collections = db.ListRootCollectionsAsync().ToList().Result;
    return string.Join(", ", collections);
}
```

I then launched the WebApplication project in the debugger, and went to the About page - my list of collections was shown.

Note that in my `bin` directory, I have both `grpc_csharp_ext.x86.dll` and`grpc_csharp_ext.x64.dll`. Could you check what's in the `bin` directory in your application when running?

Additionally, can I just check that this is a web *application* project rather than a web *site* project? The latter is known not to work with gRPC.

**Comment by babduljameel** [comment] 2018-05-21 11:03
in my bin directory, I also have both .dll listed,  rpc_csharp_ext.x86.dll andgrpc_csharp_ext.x64.dll.

This is a ASP.NET mvc web application.

**Comment by babduljameel** [comment] 2018-05-21 11:18
I am using vs2015 and the bin_path is just a variable i replaced it with actual path

**Comment by jskeet** [comment] 2018-05-21 11:19
Okay, I'll try the same test with Visual Studio 2015. So if you look at the exact path shown in the message, does the file exist?

**Comment by babduljameel** [comment] 2018-05-21 11:31
Also I am using the Google.Cloud.Firestore instead of Google.Cloud.Firestore.V1 version 1.0.0-beta03

http://nugetmusthaves.com/Package/Google.Cloud.Firestore
is the any difference

**Comment by jskeet** [comment] 2018-05-21 11:33
Apologies - Google.Cloud.Firestore is what I meant earlier on. But I assume you're using version 1.0.0-beta03?

**Comment by jskeet** [comment] 2018-05-21 12:15
Hmm. In VS2015 I'm getting an error where something (I'm not sure what) is trying to load Google.Apis.Auth, Version=1.21.0.0. I need to investigate why that is. (I suspect it's due to the relatively old version of .NET being used, but I'll need to check.)

**Comment by jskeet** [comment] 2018-05-21 13:14
Okay, so the assembly binding redirects were missing due to the order in which I'd done things, but after fixing that and updating the Newtonsoft.Json reference in the web application, this again worked fine - I didn't see the problem you ran into.

Are you able to reproduce this in a minimal project, following the steps I outlined before? It's going to be hard for me to help until I can reproduce it :(

**Comment by babduljameel** [comment] 2018-05-22 11:05
I have undone my changes by taking a backup.
just tried to update Newtonsoft.json to latest version and tried installing firestore nuget package to my ASP.NET project, but it still gives the same error

below is the list of packages that I am using do u see any other package required an nuget update

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="angularjs" version="1.6.6" targetFramework="net45" />
  <package id="AngularJS.Core" version="1.6.5" targetFramework="net45" />
  <package id="AngularJS.Resource" version="1.6.5" targetFramework="net45" />
  <package id="AngularJS.Utils.Pagination" version="0.11.1" targetFramework="net45" />
  <package id="Antlr" version="3.4.1.9004" targetFramework="net45" />
  <package id="AttributeRouting.Core" version="3.5.6" targetFramework="net45" />
  <package id="AttributeRouting.Core.Http" version="3.5.6" targetFramework="net45" />
  <package id="AttributeRouting.Core.Web" version="3.5.6" targetFramework="net45" />
  <package id="bootstrap" version="3.3.7" targetFramework="net45" />
  <package id="CacheCow.Common" version="1.2.3" targetFramework="net45" />
  <package id="CacheCow.Server" version="1.2.3" targetFramework="net45" />
  <package id="CommonServiceLocator" version="1.3" targetFramework="net45" />
  <package id="elmah.corelibrary" version="1.2.2" targetFramework="net45" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  <package id="Google.Api.CommonProtos" version="1.2.0" targetFramework="net451" />
  <package id="Google.Api.Gax" version="2.3.0" targetFramework="net451" />
  <package id="Google.Api.Gax.Grpc" version="2.3.0" targetFramework="net451" />
  <package id="Google.Apis" version="1.32.2" targetFramework="net451" />
  <package id="Google.Apis.Auth" version="1.32.2" targetFramework="net451" />
  <package id="Google.Apis.Core" version="1.32.2" targetFramework="net451" />
  <package id="Google.Cloud.Firestore" version="1.0.0-beta03" targetFramework="net451" />
  <package id="Google.Cloud.Firestore.V1Beta1" version="1.0.0-beta03" targetFramework="net451" />
  <package id="Google.LongRunning" version="1.0.0" targetFramework="net451" />
  <package id="Google.Protobuf" version="3.5.1" targetFramework="net451" />
  <package id="Grpc.Auth" version="1.10.0" targetFramework="net451" />
  <package id="Grpc.Core" version="1.10.0" targetFramework="net451" />
  <package id="jQuery" version="3.1.0" targetFramework="net45" />
  <package id="jQuery.MaskedInput" version="1.4.1.0" targetFramework="net45" />
  <package id="jQuery.UI.Combined" version="1.12.1" targetFramework="net45" />
  <package id="jQuery.Validation" version="1.16.0" targetFramework="net45" />
  <package id="jquery-timepicker-jt" version="1.11.11" targetFramework="net45" />
  <package id="knockoutjs" version="3.4.2" targetFramework="net45" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.Mvc" version="4.0.20710.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Razor" version="2.0.20710.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.HelpPage" version="4.0.30506" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages" version="2.0.20710.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages.Data" version="2.0.20710.0" targetFramework="net45" />
  <package id="Microsoft.AspNet.WebPages.WebData" version="2.0.20710.0" targetFramework="net45" />
  <package id="Microsoft.Data.Edm" version="5.6.0" targetFramework="net45" />
  <package id="Microsoft.Data.OData" version="5.6.0" targetFramework="net45" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.0.0" targetFramework="net45" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.0.0" targetFramework="net45" />
  <package id="Microsoft.OData.Core" version="7.2.0" targetFramework="net45" />
  <package id="Microsoft.OData.Edm" version="7.2.0" targetFramework="net45" />
  <package id="Microsoft.Spatial" version="7.2.0" targetFramework="net45" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net451" />
  <package id="NLog" version="4.4.5" targetFramework="net45" />
  <package id="NLog.Config" version="4.4.5" targetFramework="net45" />
  <package id="NLog.Schema" version="4.4.5" targetFramework="net45" />
  <package id="PagedList" version="1.17.0.0" targetFramework="net45" />
  <package id="PagedList.Mvc" version="4.5.0.0" targetFramework="net45" />
  <package id="smalot.bootstrap-datetimepicker" version="1.0.4" targetFramework="net45" />
  <package id="System.Collections" version="4.0.11" targetFramework="net45" />
  <package id="System.Collections.Concurrent" version="4.0.12" targetFramework="net45" />
  <package id="System.Collections.Immutable" version="1.4.0" targetFramework="net451" />
  <package id="System.ComponentModel" version="4.0.1" targetFramework="net45" />
  <package id="System.Diagnostics.Debug" version="4.0.11" targetFramework="net45" />
  <package id="System.Globalization" version="4.0.11" targetFramework="net45" />
  <package id="System.Interactive.Async" version="3.1.1" targetFramework="net451" />
  <package id="System.Linq" version="4.1.0" targetFramework="net45" />
  <package id="System.Linq.Dynamic" version="1.0.7" targetFramework="net45" />
  <package id="System.Linq.Expressions" version="4.1.0" targetFramework="net45" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net451" />
  <package id="System.Reflection" version="4.1.0" targetFramework="net45" />
  <package id="System.Resources.ResourceManager" version="4.0.1" targetFramework="net45" />
  <package id="System.Runtime.Extensions" version="4.1.0" targetFramework="net45" />
  <package id="System.Spatial" version="5.6.0" targetFramework="net45" />
  <package id="System.Threading" version="4.0.11" targetFramework="net45" />
  <package id="System.Threading.Tasks" version="4.0.11" targetFramework="net45" />
  <package id="taglib" version="2.1.0.0" targetFramework="net451" />
  <package id="Twitter.Typeahead" version="0.11.1" targetFramework="net45" />
  <package id="Unity" version="4.0.1" targetFramework="net45" />
  <package id="Unity.Mvc" version="4.0.1" targetFramework="net45" />
  <package id="Unity.WebAPI" version="5.2.3" targetFramework="net45" />
  <package id="WebActivator" version="1.0.0.0" targetFramework="net45" />
  <package id="WebActivatorEx" version="2.0" targetFramework="net45" />
  <package id="WebGrease" version="1.6.0" targetFramework="net45" />
  <package id="WebMatrix.WebData" version="2.0.30506.0" targetFramework="net45" />
</packages>`

**Comment by jskeet** [comment] 2018-05-22 11:21
Rather than trying to change your existing project, are you able to reproduce the problem with a new project, following the steps I described earlier? If that works, then we can try to spot the difference between the working and not-working projects on your machine. If it doesn't work, we can try to spot the difference between the working project on my machine and the not-working project on your machine - but it'll be nice and simple.

**Comment by babduljameel** [comment] 2018-05-22 11:31
I just tried this, I have created a new ASP.NET solution with ,NET 4.5.1 and added firestore nuget and relaunch the application, the application load is fine

**Comment by jskeet** [comment] 2018-05-22 11:34
So that's adding it directly to the ASP.NET project - what about if you have two projects in the solution, which as I understand it is closer to your "real" setup, and is what I tried?

Also, could you provide the full stack trace of the exception when it's failing? It would be interesting to know more about that.

**Comment by jskeet** [comment] 2018-05-23 09:06
Hmm... that may well be very relevant. I'm not familiar with `WebActivator` - perhaps that's trying to load the native DLL as if it's a managed DLL?

**Comment by babduljameel** [comment] 2018-05-23 10:02
it make sense. i have updated WebActivator to latest version and the ASP.NET project started working here is the  [https://stackoverflow.com/questions/18325799/could-not-load-file-or-assembly-hunspellx64-dll-while-using-nhunspell-nuget-pack/18328207](solution)

thanks for all your help.

**Comment by jskeet** [comment] 2018-05-23 10:03
Good to know, thanks. Will close this issue.

**Closed by jskeet** 2018-05-23 10:03 UTC
