### ISSUE TITLE
Memory Leak in GoogleStackdriverAppender

### ISSUE THREAD

**Issue by psyonix-luis** [GoogleCloudPlatform/google-cloud-dotnet#1502] opened 2017-09-29 02:38 UTC
Using the GoogleStackdriver, running a load test (or even with minimal traffic, just letting it run over time) I'm seeing memory leak at a few MB/min. 

Grpc.Core.Metadata+Entry, Grpc.Core.Metadata and Grpc.Core.Internal.AsyncCall<Google.Cloud.Logging.V2.WriteLogEntriesRequest> were the big suspects. They all dig down to the AsyncCall > Action > CancellationCallbackInfo but not sure what it may entail.

Heap dump: https://i.imgur.com/5pvc3Iu.jpg

I tested this both with the programmatic way of adding the GoogleStackdriverAppender as well as via log4net config. I'm adding resource labels and custom labels, but I also tried just barebones logging and it was still leaking at the same rate. I played around with setting the MaxMemoryCount / MaxMemorySize / MaxUploadBatchSize to different values, but no matter how small or how large I still leak. (If set too low I start losing messages). I initially thought the async calls were getting backed up, but when I slowed down the load, issue was still there.

Here's how I'm adding the appender:
```var googleAppender = new GoogleStackdriverAppender();
var googleAppender = new GoogleStackdriverAppender();
googleAppender.Name = "CloudLogger";
googleAppender.ProjectId = Settings.GoogleCloudProjectID;
googleAppender.LogId = "GoogleStackdriverAppender";
googleAppender.MaxMemoryCount = 2000; // defaults value is 1000. ref: https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Logging.Log4Net/api/Google.Cloud.Logging.Log4Net.GoogleStackdriverAppender.html#Google_Cloud_Logging_Log4Net_GoogleStackdriverAppender_MaxMemoryCount
googleAppender.MaxUploadBatchSize = 200;
// Set custom layout for text payload
PatternLayout layout = new PatternLayout("%property{socketid}  %logger - %message");
layout.ActivateOptions();
googleAppender.Layout = layout;

// Set instance information, otherwise this will fall under the "global" logs
googleAppender.ResourceType = "gce_instance";
googleAppender.AddResourceLabel(new GoogleStackdriverAppender.Label()
{
	Key = "instance_id",
	Value = Settings.InstanceID
});

var version = Assembly.GetEntryAssembly().GetName().Version.ToString();
googleAppender.AddCustomLabel(new GoogleStackdriverAppender.Label()
{
	Key = "version",
	Value = version
});

googleAppender.ActivateOptions();
repo.Root.AddAppender(googleAppender);```

**Comment by jskeet** [comment] 2017-09-29 06:59
Ian, could you take a look and assign a priority/label appropriately?

@psyonix-luis could you give details about which package versions you're using? (I know there was a leak in Grpc.Core a while ago, but that's been fixed, so if you're using reasonably recent packages I wouldn't expect that to be the cause.)

**Comment by iantalarico** [comment] 2017-09-29 13:42
@jskeet This is in the log4net code so I don't have as much insight.

@chrisdunelm Chris can you take a look into this?  If not I can but I have less knowledge here.  Feel free to send back to me if need be.  I labeled as a P1 but may be a P0 depending on the leak?

**Comment by chrisdunelm** [comment] 2017-09-29 13:59
@iantalarico Yes, I'll take a look, but after @psyonix-luis has confirmed the version of Grpc.Core that's being used. As @jskeet said, there was a known memory leak in a previous version.

**Comment by psyonix-luis** [comment] 2017-09-29 17:11
Hi @chrisdunelm , I'm using "Google.Cloud.Logging.Log4Net" Version="2.1.0" (which uses Google.Cloud.Logging.V2 2.0.0)

**Comment by chrisdunelm** [comment] 2017-09-29 17:17
@psyonix-luis Thanks. I've just noticed that `Google.Cloud.Logging.Log4Net` v2.1.0 depends on `Grpc.Core` v1.4.0, which I'm fairly sure contains the known memory leak.
Please can you add a direct dependency from your project to `Grpc.Core` v1.6.1 (latest). I'm fairly confident using this latest version of `Grpc.Core` will fix the problem; please can you let me know if it does.

It looks like we should have pushed an updated version of `Google.Cloud.Logging.Log4Net`, which we'll do sometime next week, which depends on the latest `Grpc.Core`.

**Comment by jskeet** [comment] 2017-09-29 17:20
Unfortunately not - the memory leak I'm aware of was [fixed in 1.4.0](https://github.com/grpc/grpc/releases/tag/v1.4.0). It was 1.3.x and earlier that had the leak. This may be a different problem :(

**Comment by psyonix-luis** [comment] 2017-09-29 17:26
Tried again with Grpc.Core 1.6.1, heap snapshot looks the same unfortunately

**Comment by chrisdunelm** [comment] 2017-09-29 17:30
OK, sorry, my mistake. I'll look into this next week.

**Comment by psyonix-luis** [comment] 2017-10-02 22:42
So my guess from a quick investigation is that the leak is here : https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/AsyncCall.cs#L408

Based on:
https://stackoverflow.com/questions/14627226/why-is-my-async-await-with-cancellationtokensource-leaking-memory
https://github.com/aws/aws-sdk-net/issues/361

Wasn't able to compile grpc.core to test it out though :(

**Comment by chrisdunelm** [comment] 2017-10-03 10:53
@psyonix-luis thanks for the investigation. I agree with you for the likely cause of the problem. I'm doing some testing to make sure, then I'll work to get it fixed.

**Comment by chrisdunelm** [comment] 2017-10-04 10:11
It looks like the gRPC fix [PR#12801](https://github.com/grpc/grpc/pull/12801) should be in the 1.7.0 release. I'm not sure of the exact timescale for this, but it is expected within the next few weeks. Once it's released we'll update our dependencies and release new versions of Google.Cloud.* packages.

**Comment by psyonix-luis** [comment] 2017-10-04 17:13
Awesome, thanks for the very quick responses. Looking forward to it!

**Comment by chrisdunelm** [comment] 2017-10-27 11:40
gRPC 1.7.0 has now been released, which fixes this issue.
With the next few days we'll rebuild the logging packages with updated dependency on gRPC 1.7.0, which will fix this bug.

**Comment by sebbov** [comment] 2017-11-16 13:22
Any update or specific ETA?

I believe we're hitting the same issue.  We use Google.Cloud.Logging.Log4Net 2.1.0, Google.Cloud.Logging.V2 2.0.0, and see a leak, resulting in server instances dying on a daily basis, with a sample heap dump (well before oom'ing):

```
(lldb) dumpheap -stat
Statistics:
              MT    Count    TotalSize Class Name
[...]
00007fb15c705508   251630     10065200 Grpc.Core.Metadata+Entry
00007fb15c827b48   188725     10568568 Grpc.Core.Metadata+Entry[]
00007fb15c8b1450    62907     16104192 Grpc.Core.Internal.AsyncCall`2[[Google.Cloud.Logging.V2.WriteLogEntriesRequest, Google.Cloud.Logging.V2],[Google.Cloud.Logging.V2.WriteLogEntriesResponse, Google.Cloud.Logging.V2]]
00007fb15a49b460   451971     26389576 System.String
```

thanks!

**Comment by jskeet** [comment] 2017-11-16 13:24
@sebbov: You should be able to add a manual dependency to Grpc.Core 1.7.1 (as 1.7.1 included another memory leak fix over 1.7.0). We'll still be hoping to do a release that depends on that version, but it means you're not gated on the release - and in particular, if you still notice any problems, that suggests there's a different issue.

**Comment by sebbov** [comment] 2017-11-16 18:02
@jskeet Using Grpc.Core 1.7.1 indeed fixes it.  The memory usage is stable now under load.  Thanks!

**Comment by jskeet** [comment] 2017-11-16 18:08
@sebbov: Thanks so much for testing it - that's really good to know. (And there's no reason why you shouldn't keep that explicit dependency until we've shipped a new package - it's not like this is a hacky workaround that might break; it's just an alternative way of getting to the same code.)

**Comment by sebbov** [comment] 2017-11-16 18:14
@jskeet Yup, left a TODO to remove it once you've shipped the new package, depending on the fixed up Grpc.Core.

**Comment by jskeet** [comment] 2017-11-27 15:18
The 2.2.0 Log4Net appender is [now available](https://www.nuget.org/packages/Google.Cloud.Logging.Log4Net/2.2.0). Closing.

**Closed by jskeet** 2017-11-27 15:18 UTC
Labels: api: logging, priority: p1, type: bug
