### ISSUE TITLE
I need a newer version of the Google.Cloud.Storage.V1 package

### ISSUE THREAD

**Issue by sebagomez** [GoogleCloudPlatform/google-cloud-dotnet#1283] opened 2017-07-27 15:37 UTC
In my dll I reference Google.Cloud.StorageV1 and many other Google SDK dlls, but I can't have the latest version of all of them together.
It's referencing old packages, thus I can't have newer packages with this version of this package :(

So at runtime I get: 
> System.IO.FileLoadException: Could not load file or assembly 'Google.Apis.Auth, Version=1.27.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

![image](https://user-images.githubusercontent.com/1637983/28678948-138c6b4e-72c8-11e7-80b6-b608ce165715.png)

**Comment by jskeet** [comment] 2017-07-27 15:49
What kind of project is this? It would be good to resolve this - issue #1280 is very similar.

It should be absolutely fine to use Google.Apis.Core v1.28.0.0 to satisfy a requirement for v1.27.1.0. I'd expect an assembly binding redirect to be generated automatically in regular .NET, and for .NET Core to "just do the right thing".

If you could provide a minimal example with details such as project type, target framework etc I'll try to dig deeper. (I'm on vacation this week so it'll be next week before I'm able to devote much time to this, but I do want to get to the bottom of it.)

**Comment by sebagomez** [comment] 2017-07-27 16:56
wow, that was fast!
My project is a "regular" 4.5.2 .net framework Class Library. I cannot send you the exact lib but it's a very simple scenario. Let me know if you need more info.

**Comment by jskeet** [comment] 2017-07-27 18:51
Hmm... I don't see that style of References in Solution Explorer for a regular class library (rather than a .NET Core class library). I've tried installing Google.Apis.Storage.v1 (which installs 1.28.0 of everything) and then Google.Cloud.Storage.V1 v2.1.0-alpha01 (which depends on 1.27.1) and all seems fine.

If you could reproduce this in a clean solution, it would be much appreciated...

**Comment by sebagomez** [comment] 2017-07-28 15:44
I'm sorry, I could reproduce it on a clean environment. I fixed my project bringing back to 1.27.1 some of the dependencies. I had updated the dependencies and that broke everything.
Here are the steps in my prod environment and had broken. (not reproduced in a clean solution, but still)
I added a reference to Google.Cloud.Storage.V1, that added that reference and its dependencies, but most dependencies were not in the latest version, so I updated those, and that's when errors showed up. Don't know I can't reproduce it thou. I must be something else I can't realize, but it got fixed once I downgraded Google.APIs, Google.APIs.Core, Google.APIs.Auth and Google.APIs.Storage.v1

**Comment by jskeet** [comment] 2017-07-28 16:00
Thanks - will try to reproduce on Monday.

**Comment by jskeet** [comment] 2017-07-31 14:37
Set to P1 as I definitely want to try to reproduce this, but I think it's going to be tricky. It's hard to know whether the "fix" is going to be in terms of documentation/FAQ or something else, but I want to get to the bottom of it as best I can.

Just to clarify, could you let me know how you're getting a references view like that? Is that in Solution Explorer, or something else? Is it possibly via an extension such as ReSharper? Is it all *building* with no issues, and just failing at execution time? (That's what's suggested by the exception, of course.) What type of application is using your class library? Basically, anything that could help me reproduce this would be welcome.

**Comment by sebagomez** [comment] 2017-07-31 15:37
The screenshot I pasted here was from [Telerik's JustDecompile](http://www.telerik.com/products/decompiler.aspx). Those were the reference of my own dll. It does build with no issues, the exception was thrown at runtime. It was a Console App that was referencing my dll, which had references to the NuGet packages I mentioned before. 

I'm sorry I can't reproduce it on a small clean solution :(

**Comment by jskeet** [comment] 2017-07-31 15:42
Ah, that would make sense of the screenshot then. It was a console app that I tried before without reproducing the problem too.

Out of interest, do you still have the solution in a broken state so we could compare aspects of it with the "clean" version, or have you cleared out all the brokenness now?

**Comment by sebagomez** [comment] 2017-07-31 16:51
I cleared out by moving some packages back to their previous version (1.27), sorry, I had to move along

**Comment by jskeet** [comment] 2017-07-31 17:08
Completely understood. Will keep trying to reproduce :)

**Comment by jskeet** [comment] 2017-08-01 10:50
Now I understand #1280, I don't think this is related after all.

**Comment by jskeet** [comment] 2017-08-01 12:38
Okay, I've reproduced now, but only by manually editing the `.config` file of the executable. It should look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Storage.v1" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.28.0.888" newVersion="1.28.0.888" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.28.0.0" newVersion="1.28.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.28.0.0" newVersion="1.28.0.0" />
      </dependentAssembly>
    </assemblyBinding>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Core" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.28.0.0" newVersion="1.28.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Without the `assemblyBinding` elements, it fails. With it as above, it's fine - even though JustDecompile *will* show those warning triangles within `Google.Cloud.Storage.V1`.

Basically, it looks like everything about the package is fine - it's just that some way in which you did the NuGet update didn't sort the assembly binding redirects. I believe that can happen if you manually edit `packages.config` for example.

I'm going to close this issue as there's nothing we can really do about it - if it happens again, I suggest you carefully check the assembly binding redirects.

**Closed by jskeet** 2017-08-01 12:38 UTC
Labels: API: storage, Priority: P1

**Comment by sebagomez** [comment] 2017-08-01 13:16
I did not edited manually, but thanks for the heads up

**Comment by jskeet** [comment] 2017-08-01 13:32
@sebagomez: Yup, that's only *one* way it can get screwed up - but it's the *kind* of thing that does it. I don't know of a good way of saying to Visual Studio "Please recreate all my binding redirects from scratch" unfortunately :(

**Comment by benwulfe** [comment] 2017-08-01 14:07
I believe there is a nuget command for rebuilding binding redirects.

https://weblog.west-wind.com/posts/2014/Nov/29/Updating-Assembly-Redirects-with-NuGet

So if this happens again, you could try that as a first step.


On Aug 1, 2017 6:32 AM, "Jon Skeet" <notifications@github.com> wrote:

@sebagomez <https://github.com/sebagomez>: Yup, that's only *one* way it
can get screwed up - but it's the *kind* of thing that does it. I don't
know of a good way of saying to Visual Studio "Please recreate all my
binding redirects from scratch" unfortunately :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1283#issuecomment-319370867>,
or mute the thread
